; Listing generated by Microsoft (R) Optimizing Compiler Version 19.37.32822.0 

include listing.inc

INCLUDELIB OLDNAMES

EXTRN	__imp_WSACleanup:PROC
EXTRN	__imp_WSAStartup:PROC
EXTRN	atexit:PROC
PUBLIC	??1NetworkInit@@QEAA@XZ				; NetworkInit::~NetworkInit
PUBLIC	??0NetworkInit@@QEAA@XZ				; NetworkInit::NetworkInit
PUBLIC	?NetworkInitGlobal@@3UNetworkInit@@A		; NetworkInitGlobal
?NetworkInitGlobal@@3UNetworkInit@@A DB 01H DUP (?)	; NetworkInitGlobal
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__ENetworkInitGlobal@@YAXXZ DD imagerel ??__ENetworkInitGlobal@@YAXXZ
	DD	imagerel ??__ENetworkInitGlobal@@YAXXZ+77
	DD	imagerel $unwind$??__ENetworkInitGlobal@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0NetworkInit@@QEAA@XZ DD imagerel $LN4
	DD	imagerel $LN4+72
	DD	imagerel $unwind$??0NetworkInit@@QEAA@XZ
?NetworkInitGlobal$initializer$@@3P6AXXZEA DQ FLAT:??__ENetworkInitGlobal@@YAXXZ ; NetworkInitGlobal$initializer$
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0NetworkInit@@QEAA@XZ DD 021919H
	DD	03b0107H
	DD	imagerel __GSHandlerCheck
	DD	01c0H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__ENetworkInitGlobal@@YAXXZ DD 021919H
	DD	03b0107H
	DD	imagerel __GSHandlerCheck
	DD	01c0H
; Function compile flags: /Ogtpy
;	COMDAT ??0NetworkInit@@QEAA@XZ
_TEXT	SEGMENT
wsaData$ = 32
__$ArrayPad$ = 448
this$dead$ = 480
??0NetworkInit@@QEAA@XZ PROC				; NetworkInit::NetworkInit, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\Network\Network.cpp
; Line 54
$LN4:
	sub	rsp, 472				; 000001d8H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
; Line 58
	mov	ecx, 514				; 00000202H
	lea	rdx, QWORD PTR wsaData$[rsp]
	call	QWORD PTR __imp_WSAStartup
; Line 59
	lea	rax, OFFSET FLAT:?NetworkInitGlobal@@3UNetworkInit@@A ; NetworkInitGlobal
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 472				; 000001d8H
	ret	0
??0NetworkInit@@QEAA@XZ ENDP				; NetworkInit::NetworkInit
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??1NetworkInit@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1NetworkInit@@QEAA@XZ PROC				; NetworkInit::~NetworkInit, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\Network\Network.cpp
; Line 67
	rex_jmp	QWORD PTR __imp_WSACleanup
??1NetworkInit@@QEAA@XZ ENDP				; NetworkInit::~NetworkInit
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??__ENetworkInitGlobal@@YAXXZ
text$di	SEGMENT
wsaData$1 = 32
__$ArrayPad$ = 448
??__ENetworkInitGlobal@@YAXXZ PROC			; `dynamic initializer for 'NetworkInitGlobal'', COMDAT
; File D:\Dev\GitHub\vtools\netcpy\Network\Network.cpp
; Line 72
	sub	rsp, 472				; 000001d8H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
; Line 58
	mov	ecx, 514				; 00000202H
	lea	rdx, QWORD PTR wsaData$1[rsp]
	call	QWORD PTR __imp_WSAStartup
; Line 72
	lea	rcx, OFFSET FLAT:??__FNetworkInitGlobal@@YAXXZ ; `dynamic atexit destructor for 'NetworkInitGlobal''
	call	atexit
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 472				; 000001d8H
	ret	0
??__ENetworkInitGlobal@@YAXXZ ENDP			; `dynamic initializer for 'NetworkInitGlobal''
text$di	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??__FNetworkInitGlobal@@YAXXZ
text$yd	SEGMENT
??__FNetworkInitGlobal@@YAXXZ PROC			; `dynamic atexit destructor for 'NetworkInitGlobal'', COMDAT
; File D:\Dev\GitHub\vtools\netcpy\Network\Network.cpp
; Line 67
	rex_jmp	QWORD PTR __imp_WSACleanup
??__FNetworkInitGlobal@@YAXXZ ENDP			; `dynamic atexit destructor for 'NetworkInitGlobal''
text$yd	ENDS
END
