; Listing generated by Microsoft (R) Optimizing Compiler Version 19.37.32822.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??1SysSettings@@QEAA@XZ				; SysSettings::~SysSettings
PUBLIC	??0SysSettings@@QEAA@XZ				; SysSettings::SysSettings
PUBLIC	?GSysSettings@@3VSysSettings@@A			; GSysSettings
?GSysSettings@@3VSysSettings@@A DB 01H DUP (?)		; GSysSettings
_BSS	ENDS
?GSysSettings$initializer$@@3P6AXXZEA DQ FLAT:??__EGSysSettings@@YAXXZ ; GSysSettings$initializer$
; Function compile flags: /Ogtpy
;	COMDAT ??__EGSysSettings@@YAXXZ
text$di	SEGMENT
??__EGSysSettings@@YAXXZ PROC				; `dynamic initializer for 'GSysSettings'', COMDAT
; File D:\Dev\GitHub\vtools\netcpy\System\SysSettings.cpp
; Line 48
	lea	rcx, OFFSET FLAT:??__FGSysSettings@@YAXXZ ; `dynamic atexit destructor for 'GSysSettings''
	jmp	atexit
??__EGSysSettings@@YAXXZ ENDP				; `dynamic initializer for 'GSysSettings''
text$di	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??__FGSysSettings@@YAXXZ
text$yd	SEGMENT
??__FGSysSettings@@YAXXZ PROC				; `dynamic atexit destructor for 'GSysSettings'', COMDAT
	ret	0
??__FGSysSettings@@YAXXZ ENDP				; `dynamic atexit destructor for 'GSysSettings''
text$yd	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0SysSettings@@QEAA@XZ
_TEXT	SEGMENT
this$dead$ = 8
??0SysSettings@@QEAA@XZ PROC				; SysSettings::SysSettings, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\System\SysSettings.cpp
; Line 57
	lea	rax, OFFSET FLAT:?GSysSettings@@3VSysSettings@@A ; GSysSettings
	ret	0
??0SysSettings@@QEAA@XZ ENDP				; SysSettings::SysSettings
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??1SysSettings@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1SysSettings@@QEAA@XZ PROC				; SysSettings::~SysSettings, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\System\SysSettings.cpp
; Line 65
	ret	0
??1SysSettings@@QEAA@XZ ENDP				; SysSettings::~SysSettings
_TEXT	ENDS
END
