; Listing generated by Microsoft (R) Optimizing Compiler Version 19.37.32822.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_7SysThread@@6B@				; SysThread::`vftable'
EXTRN	_Thrd_join:PROC
EXTRN	_Xtime_get_ticks:PROC
EXTRN	_Thrd_id:PROC
EXTRN	_Thrd_sleep:PROC
EXTRN	_Cnd_do_broadcast_at_thread_exit:PROC
EXTRN	_Mtx_init_in_situ:PROC
EXTRN	_Mtx_destroy_in_situ:PROC
EXTRN	_beginthreadex:PROC
EXTRN	??2@YAPEAX_KAEBUnothrow_t@std@@@Z:PROC		; operator new
;	COMDAT ??_7SysThread@@6B@
CONST	SEGMENT
??_7SysThread@@6B@ DQ FLAT:??_ESysThread@@UEAAPEAXI@Z	; SysThread::`vftable'
	DQ	FLAT:?process@SysThread@@UEAAXXZ
PUBLIC	??$?0N$0A@@?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBN@Z ; std::chrono::duration<double,std::ratio<1,1000000000> >::duration<double,std::ratio<1,1000000000> ><double,0>
PUBLIC	??$duration_cast@V?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@_JU?$ratio@$00$0DLJKMKAA@@3@$0A@@chrono@std@@YA?AV?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@@Z ; std::chrono::duration_cast<std::chrono::duration<double,std::ratio<1,1000000000> >,__int64,std::ratio<1,1000000000>,0>
PUBLIC	??$duration_cast@V?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@NU?$ratio@$00$00@3@$0A@@chrono@std@@YA?AV?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@NU?$ratio@$00$00@std@@@01@@Z ; std::chrono::duration_cast<std::chrono::duration<double,std::ratio<1,1000000000> >,double,std::ratio<1,1>,0>
PUBLIC	??$?0_JU?$ratio@$00$0DLJKMKAA@@std@@$0A@@?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@@Z ; std::chrono::duration<double,std::ratio<1,1000000000> >::duration<double,std::ratio<1,1000000000> ><__int64,std::ratio<1,1000000000>,0>
PUBLIC	??$?0NU?$ratio@$00$00@std@@$0A@@?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@NU?$ratio@$00$00@std@@@12@@Z ; std::chrono::duration<double,std::ratio<1,1000000000> >::duration<double,std::ratio<1,1000000000> ><double,std::ratio<1,1>,0>
PUBLIC	??$duration_cast@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@_JU?$ratio@$00$0JIJGIA@@3@$0A@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@01@@Z ; std::chrono::duration_cast<std::chrono::duration<__int64,std::ratio<1,1000000000> >,__int64,std::ratio<1,10000000>,0>
PUBLIC	??$duration_cast@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@_JU?$ratio@$00$00@3@$0A@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@_JU?$ratio@$00$00@std@@@01@@Z ; std::chrono::duration_cast<std::chrono::duration<__int64,std::ratio<1,1000000000> >,__int64,std::ratio<1,1>,0>
PUBLIC	?count@?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEBANXZ ; std::chrono::duration<double,std::ratio<1,1000000000> >::count
PUBLIC	??$?MNU?$ratio@$00$00@std@@_JU?$ratio@$00$0DLJKMKAA@@1@@chrono@std@@YA_NAEBV?$duration@NU?$ratio@$00$00@std@@@01@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@@Z ; std::chrono::operator<<double,std::ratio<1,1>,__int64,std::ratio<1,1000000000> >
PUBLIC	??$?0_JU?$ratio@$00$0JIJGIA@@std@@$0A@@?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@12@@Z ; std::chrono::duration<__int64,std::ratio<1,1000000000> >::duration<__int64,std::ratio<1,1000000000> ><__int64,std::ratio<1,10000000>,0>
PUBLIC	??$?0_JU?$ratio@$00$00@std@@$0A@@?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@_JU?$ratio@$00$00@std@@@12@@Z ; std::chrono::duration<__int64,std::ratio<1,1000000000> >::duration<__int64,std::ratio<1,1000000000> ><__int64,std::ratio<1,1>,0>
PUBLIC	??Z?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAAAEAV012@AEBV012@@Z ; std::chrono::duration<__int64,std::ratio<1,1000000000> >::operator-=
PUBLIC	?count@?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@std@@QEBA_JXZ ; std::chrono::duration<__int64,std::ratio<1,1000000> >::count
PUBLIC	??$_To_timespec64_sys_10_day_clamped@_JU?$ratio@$00$0DLJKMKAA@@std@@@std@@YA_NAEAU_timespec64@@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@0@@Z ; std::_To_timespec64_sys_10_day_clamped<__int64,std::ratio<1,1000000000> >
PUBLIC	??$?NUsteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@V312@@chrono@std@@YA_NAEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@01@0@Z ; std::chrono::operator<=<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> >,std::chrono::duration<__int64,std::ratio<1,1000000000> > >
PUBLIC	??$duration_cast@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@_JU?$ratio@$00$0PECEA@@3@$0A@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@@Z ; std::chrono::duration_cast<std::chrono::duration<__int64,std::ratio<1,1000000000> >,__int64,std::ratio<1,1000000>,0>
PUBLIC	??$?M_JU?$ratio@$00$0DLJKMKAA@@std@@_JU01@@chrono@std@@YA_NAEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@0@Z ; std::chrono::operator<<__int64,std::ratio<1,1000000000>,__int64,std::ratio<1,1000000000> >
PUBLIC	??$?G_JU?$ratio@$00$0DLJKMKAA@@std@@_JU?$ratio@$00$0PECEA@@1@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV201@AEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@@Z ; std::chrono::operator-<__int64,std::ratio<1,1000000000>,__int64,std::ratio<1,1000000> >
PUBLIC	??$?M_JU?$ratio@$00$0PECEA@@std@@_JU01@@chrono@std@@YA_NAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@0@Z ; std::chrono::operator<<__int64,std::ratio<1,1000000>,__int64,std::ratio<1,1000000> >
PUBLIC	??$sleep_until@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@this_thread@std@@YAXAEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@1@@Z ; std::this_thread::sleep_until<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> > >
PUBLIC	??$?0_JU?$ratio@$00$0PECEA@@std@@$0A@@?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@12@@Z ; std::chrono::duration<__int64,std::ratio<1,1000000000> >::duration<__int64,std::ratio<1,1000000000> ><__int64,std::ratio<1,1000000>,0>
PUBLIC	??$?MUsteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@V312@@chrono@std@@YA_NAEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@01@0@Z ; std::chrono::operator<<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> >,std::chrono::duration<__int64,std::ratio<1,1000000000> > >
PUBLIC	??$?GUsteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@_JU?$ratio@$00$0PECEA@@2@@chrono@std@@YA?AV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@01@AEBV201@AEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@@Z ; std::chrono::operator-<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> >,__int64,std::ratio<1,1000000> >
PUBLIC	??$?O_JU?$ratio@$00$0PECEA@@std@@_JU01@@chrono@std@@YA_NAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@0@Z ; std::chrono::operator><__int64,std::ratio<1,1000000>,__int64,std::ratio<1,1000000> >
PUBLIC	??Y?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAAAEAV012@AEBV012@@Z ; std::chrono::duration<__int64,std::ratio<1,1000000000> >::operator+=
PUBLIC	?count@?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@chrono@std@@QEBA_JXZ ; std::chrono::duration<__int64,std::ratio<1,10000000> >::count
PUBLIC	??Y?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@QEAAAEAV012@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@@Z ; std::chrono::time_point<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> > >::operator+=
PUBLIC	??$_To_absolute_time@_JU?$ratio@$00$0PECEA@@std@@@std@@YA?A_PAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@0@@Z ; std::_To_absolute_time<__int64,std::ratio<1,1000000> >
PUBLIC	??$sleep_for@_JU?$ratio@$00$0PECEA@@std@@@this_thread@std@@YAXAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@1@@Z ; std::this_thread::sleep_for<__int64,std::ratio<1,1000000> >
PUBLIC	??$?0_J$0A@@?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@std@@QEAA@AEB_J@Z ; std::chrono::duration<__int64,std::ratio<1,1000000> >::duration<__int64,std::ratio<1,1000000> ><__int64,0>
PUBLIC	??$duration_cast@V?$duration@_JU?$ratio@$00$00@std@@@chrono@std@@_JU?$ratio@$00$0DLJKMKAA@@3@$0A@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$00@std@@@01@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@@Z ; std::chrono::duration_cast<std::chrono::duration<__int64,std::ratio<1,1> >,__int64,std::ratio<1,1000000000>,0>
PUBLIC	??$?0_J$0A@@?$duration@_JU?$ratio@$00$00@std@@@chrono@std@@QEAA@AEB_J@Z ; std::chrono::duration<__int64,std::ratio<1,1> >::duration<__int64,std::ratio<1,1> ><__int64,0>
PUBLIC	??$?0_J$0A@@?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@chrono@std@@QEAA@AEB_J@Z ; std::chrono::duration<__int64,std::ratio<1,10000000> >::duration<__int64,std::ratio<1,10000000> ><__int64,0>
PUBLIC	?count@?$duration@_JU?$ratio@$00$00@std@@@chrono@std@@QEBA_JXZ ; std::chrono::duration<__int64,std::ratio<1,1> >::count
PUBLIC	?process@SysThread@@UEAAXXZ			; SysThread::process
PUBLIC	??_Gthread@std@@QEAAPEAXI@Z			; std::thread::`scalar deleting destructor'
PUBLIC	?stop@SysThread@@QEAAXXZ			; SysThread::stop
PUBLIC	??1SysThread@@UEAA@XZ				; SysThread::~SysThread
PUBLIC	??_GSysThread@@UEAAPEAXI@Z			; SysThread::`scalar deleting destructor'
PUBLIC	??1mutex@std@@QEAA@XZ				; std::mutex::~mutex
PUBLIC	??1SysMutex@@QEAA@XZ				; SysMutex::~SysMutex
PUBLIC	??0SysMutex@@QEAA@XZ				; SysMutex::SysMutex
PUBLIC	??0mutex@std@@QEAA@XZ				; std::mutex::mutex
PUBLIC	??1_Mutex_base@std@@QEAA@XZ			; std::_Mutex_base::~_Mutex_base
PUBLIC	??0_Mutex_base@std@@QEAA@H@Z			; std::_Mutex_base::_Mutex_base
PUBLIC	?SysSleep@@YAXN@Z				; SysSleep
PUBLIC	?join@thread@std@@QEAAXXZ			; std::thread::join
PUBLIC	?joinable@thread@std@@QEBA_NXZ			; std::thread::joinable
PUBLIC	??1thread@std@@QEAA@XZ				; std::thread::~thread
PUBLIC	?terminate@std@@YAXXZ				; std::terminate
PUBLIC	?count@?$duration@NU?$ratio@$00$00@std@@@chrono@std@@QEBANXZ ; std::chrono::duration<double,std::ratio<1,1> >::count
EXTRN	??_ESysThread@@UEAAPEAXI@Z:PROC			; SysThread::`vector deleting destructor'
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_To_timespec64_sys_10_day_clamped@_JU?$ratio@$00$0DLJKMKAA@@std@@@std@@YA_NAEAU_timespec64@@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@0@@Z DD imagerel $LN137
	DD	imagerel $LN137+142
	DD	imagerel $unwind$??$_To_timespec64_sys_10_day_clamped@_JU?$ratio@$00$0DLJKMKAA@@std@@@std@@YA_NAEAU_timespec64@@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@0@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$sleep_until@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@this_thread@std@@YAXAEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@1@@Z DD imagerel $LN182
	DD	imagerel $LN182+277
	DD	imagerel $unwind$??$sleep_until@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@this_thread@std@@YAXAEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@1@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_To_absolute_time@_JU?$ratio@$00$0PECEA@@std@@@std@@YA?A_PAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@0@@Z DD imagerel $LN85
	DD	imagerel $LN85+166
	DD	imagerel $unwind$??$_To_absolute_time@_JU?$ratio@$00$0PECEA@@std@@@std@@YA?A_PAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@0@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$sleep_for@_JU?$ratio@$00$0PECEA@@std@@@this_thread@std@@YAXAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@1@@Z DD imagerel $LN268
	DD	imagerel $LN268+382
	DD	imagerel $unwind$??$sleep_for@_JU?$ratio@$00$0PECEA@@std@@@this_thread@std@@YAXAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@1@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_Gthread@std@@QEAAPEAXI@Z DD imagerel $LN14
	DD	imagerel $LN14+40
	DD	imagerel $unwind$??_Gthread@std@@QEAAPEAXI@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?stop@SysThread@@QEAAXXZ DD imagerel $LN55
	DD	imagerel $LN55+20
	DD	imagerel $unwind$?stop@SysThread@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$?stop@SysThread@@QEAAXXZ DD imagerel $LN55+20
	DD	imagerel $LN55+140
	DD	imagerel $chain$0$?stop@SysThread@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$?stop@SysThread@@QEAAXXZ DD imagerel $LN55+140
	DD	imagerel $LN55+146
	DD	imagerel $chain$1$?stop@SysThread@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$?stop@SysThread@@QEAAXXZ DD imagerel $LN55+146
	DD	imagerel $LN55+203
	DD	imagerel $chain$2$?stop@SysThread@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1SysThread@@UEAA@XZ DD imagerel $LN11
	DD	imagerel $LN11+38
	DD	imagerel $unwind$??1SysThread@@UEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_GSysThread@@UEAAPEAXI@Z DD imagerel $LN16
	DD	imagerel $LN16+71
	DD	imagerel $unwind$??_GSysThread@@UEAAPEAXI@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0SysMutex@@QEAA@XZ DD imagerel $LN9
	DD	imagerel $LN9+33
	DD	imagerel $unwind$??0SysMutex@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0mutex@std@@QEAA@XZ DD imagerel $LN7
	DD	imagerel $LN7+33
	DD	imagerel $unwind$??0mutex@std@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0_Mutex_base@std@@QEAA@H@Z DD imagerel $LN4
	DD	imagerel $LN4+33
	DD	imagerel $unwind$??0_Mutex_base@std@@QEAA@H@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?SysSleep@@YAXN@Z DD imagerel $LN272
	DD	imagerel $LN272+366
	DD	imagerel $unwind$?SysSleep@@YAXN@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?join@thread@std@@QEAAXXZ DD imagerel $LN16
	DD	imagerel $LN16+94
	DD	imagerel $unwind$?join@thread@std@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1thread@std@@QEAA@XZ DD imagerel $LN9
	DD	imagerel $LN9+21
	DD	imagerel $unwind$??1thread@std@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?terminate@std@@YAXXZ DD imagerel $LN4
	DD	imagerel $LN4+10
	DD	imagerel $unwind$?terminate@std@@YAXXZ
;	COMDAT xdata
xdata	SEGMENT
$unwind$?terminate@std@@YAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1thread@std@@QEAA@XZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?join@thread@std@@QEAAXXZ DD 020601H
	DD	030025206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?SysSleep@@YAXN@Z DD 0a2819H
	DD	046819H
	DD	0e6414H
	DD	0d5414H
	DD	0c3414H
	DD	070109214H
	DD	imagerel __GSHandlerCheck
	DD	030H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0_Mutex_base@std@@QEAA@H@Z DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0mutex@std@@QEAA@XZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0SysMutex@@QEAA@XZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_GSysThread@@UEAAPEAXI@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1SysThread@@UEAA@XZ DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$?stop@SysThread@@QEAAXXZ DD 020021H
	DD	087400H
	DD	imagerel $LN55
	DD	imagerel $LN55+20
	DD	imagerel $unwind$?stop@SysThread@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$?stop@SysThread@@QEAAXXZ DD 021H
	DD	imagerel $LN55
	DD	imagerel $LN55+20
	DD	imagerel $unwind$?stop@SysThread@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$?stop@SysThread@@QEAAXXZ DD 020521H
	DD	087405H
	DD	imagerel $LN55
	DD	imagerel $LN55+20
	DD	imagerel $unwind$?stop@SysThread@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?stop@SysThread@@QEAAXXZ DD 020601H
	DD	030025206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_Gthread@std@@QEAAPEAXI@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$sleep_for@_JU?$ratio@$00$0PECEA@@std@@@this_thread@std@@YAXAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@1@@Z DD 0a2819H
	DD	046819H
	DD	0e6414H
	DD	0d5414H
	DD	0c3414H
	DD	070109214H
	DD	imagerel __GSHandlerCheck
	DD	030H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_To_absolute_time@_JU?$ratio@$00$0PECEA@@std@@@std@@YA?A_PAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@0@@Z DD 060f01H
	DD	07640fH
	DD	06340fH
	DD	0700b320fH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$sleep_until@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@this_thread@std@@YAXAEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@1@@Z DD 0a2819H
	DD	046819H
	DD	0e6414H
	DD	0d5414H
	DD	0c3414H
	DD	070109214H
	DD	imagerel __GSHandlerCheck
	DD	030H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_To_timespec64_sys_10_day_clamped@_JU?$ratio@$00$0DLJKMKAA@@std@@@std@@YA_NAEAU_timespec64@@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@0@@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
; Function compile flags: /Ogtpy
;	COMDAT ?count@?$duration@NU?$ratio@$00$00@std@@@chrono@std@@QEBANXZ
_TEXT	SEGMENT
this$ = 8
?count@?$duration@NU?$ratio@$00$00@std@@@chrono@std@@QEBANXZ PROC ; std::chrono::duration<double,std::ratio<1,1> >::count, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 110
	movsd	xmm0, QWORD PTR [rcx]
; Line 111
	ret	0
?count@?$duration@NU?$ratio@$00$00@std@@@chrono@std@@QEBANXZ ENDP ; std::chrono::duration<double,std::ratio<1,1> >::count
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?terminate@std@@YAXXZ
_TEXT	SEGMENT
?terminate@std@@YAXXZ PROC				; std::terminate, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\exception
; Line 175
$LN4:
	sub	rsp, 40					; 00000028H
; Line 177
	call	abort
	int	3
$LN3@terminate:
?terminate@std@@YAXXZ ENDP				; std::terminate
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??1thread@std@@QEAA@XZ
_TEXT	SEGMENT
this$ = 48
??1thread@std@@QEAA@XZ PROC				; std::thread::~thread, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 91
$LN9:
	sub	rsp, 40					; 00000028H
; Line 116
	cmp	DWORD PTR [rcx+8], 0
; Line 92
	jne	SHORT $LN8@thread
; Line 95
	add	rsp, 40					; 00000028H
	ret	0
$LN8@thread:
; Line 93
	call	?terminate@std@@YAXXZ			; std::terminate
	int	3
$LN6@thread:
??1thread@std@@QEAA@XZ ENDP				; std::thread::~thread
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?joinable@thread@std@@QEBA_NXZ
_TEXT	SEGMENT
this$ = 8
?joinable@thread@std@@QEBA_NXZ PROC			; std::thread::joinable, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 116
	cmp	DWORD PTR [rcx+8], 0
	setne	al
; Line 117
	ret	0
?joinable@thread@std@@QEBA_NXZ ENDP			; std::thread::joinable
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?join@thread@std@@QEAAXXZ
_TEXT	SEGMENT
$T1 = 32
this$ = 64
?join@thread@std@@QEAAXXZ PROC				; std::thread::join, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 119
$LN16:
	push	rbx
	sub	rsp, 48					; 00000030H
; Line 116
	cmp	DWORD PTR [rcx+8], 0
; Line 119
	mov	rbx, rcx
; Line 120
	je	SHORT $LN13@join
; Line 124
	call	_Thrd_id
	cmp	DWORD PTR [rbx+8], eax
	je	SHORT $LN14@join
; Line 128
	movups	xmm0, XMMWORD PTR [rbx]
	xor	edx, edx
	lea	rcx, QWORD PTR $T1[rsp]
	movaps	XMMWORD PTR $T1[rsp], xmm0
	call	_Thrd_join
	test	eax, eax
	jne	SHORT $LN15@join
; Line 132
	xorps	xmm0, xmm0
	movups	XMMWORD PTR [rbx], xmm0
; Line 133
	add	rsp, 48					; 00000030H
	pop	rbx
	ret	0
$LN13@join:
; Line 121
	mov	ecx, 1
	call	?_Throw_Cpp_error@std@@YAXH@Z		; std::_Throw_Cpp_error
	int	3
$LN14@join:
; Line 125
	mov	ecx, 5
	call	?_Throw_Cpp_error@std@@YAXH@Z		; std::_Throw_Cpp_error
	int	3
$LN15@join:
; Line 129
	mov	ecx, 2
	call	?_Throw_Cpp_error@std@@YAXH@Z		; std::_Throw_Cpp_error
	int	3
$LN11@join:
?join@thread@std@@QEAAXXZ ENDP				; std::thread::join
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?SysSleep@@YAXN@Z
_TEXT	SEGMENT
_Tgt$1 = 32
__$ArrayPad$ = 48
seconds$dead$ = 96
?SysSleep@@YAXN@Z PROC					; SysSleep, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\System\SysSleep.h
; Line 55
$LN272:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rbp
	mov	QWORD PTR [rsp+24], rsi
	push	rdi
	sub	rsp, 80					; 00000050H
	movaps	XMMWORD PTR [rsp+64], xmm6
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 670
	call	_Query_perf_frequency
	mov	rbx, rax
; Line 671
	call	_Query_perf_counter
; Line 677
	cmp	rbx, 10000000				; 00989680H
	jne	SHORT $LN13@SysSleep
; Line 680
	imul	rax, rax, 100				; 00000064H
	jmp	SHORT $LN14@SysSleep
$LN13@SysSleep:
; Line 688
	cdq
	idiv	rbx
	mov	rcx, rax
	imul	rax, rdx, 1000000000			; 3b9aca00H
	imul	rcx, rcx, 1000000000			; 3b9aca00H
	cdq
	idiv	rbx
; Line 689
	add	rax, rcx
$LN14@SysSleep:
; Line 212
	mov	rcx, 9223372036844775807		; 7fffffffff67697fH
; Line 142
	lea	rdi, QWORD PTR [rax+10000000]
; Line 212
	cmp	rax, rcx
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 168
	jl	SHORT $LN265@SysSleep
; Line 171
	mov	rdi, 9223372036854775807		; 7fffffffffffffffH
$LN265@SysSleep:
	movsd	xmm6, QWORD PTR __real@43088e6d68b00000
	mov	rsi, 864000000000000			; 000311cdad160000H
	mov	rbp, 1237940039285380275		; 112e0be826d694b3H
	npad	2
$LL87@SysSleep:
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 670
	call	_Query_perf_frequency
	mov	rbx, rax
; Line 671
	call	_Query_perf_counter
; Line 677
	cmp	rbx, 10000000				; 00989680H
	jne	SHORT $LN93@SysSleep
; Line 680
	imul	rax, rax, 100				; 00000064H
	jmp	SHORT $LN94@SysSleep
$LN93@SysSleep:
; Line 688
	cdq
	idiv	rbx
	mov	rcx, rax
	imul	rax, rdx, 1000000000			; 3b9aca00H
	imul	rcx, rcx, 1000000000			; 3b9aca00H
	cdq
	idiv	rbx
; Line 689
	add	rax, rcx
$LN94@SysSleep:
; Line 212
	cmp	rax, rdi
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 191
	jge	SHORT $LN260@SysSleep
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 212
	mov	rbx, rdi
	sub	rbx, rax
; Line 706
	call	_Xtime_get_ticks
; Line 436
	imul	rdx, rax, 100				; 00000064H
	xorps	xmm0, xmm0
; Line 434
	cvtsi2sd xmm0, rbx
; Line 99
	comisd	xmm0, xmm6
; Line 142
	lea	rcx, QWORD PTR [rdx+rsi]
; Line 708
	ja	SHORT $LN126@SysSleep
; Line 99
	lea	rcx, QWORD PTR [rdx+rbx]
$LN126@SysSleep:
; Line 441
	lea	rax, QWORD PTR [rdx+rbx]
	add	rdx, rsi
	comisd	xmm0, xmm6
	cmovbe	rdx, rax
	mov	rax, rbp
	imul	rdx
	sar	rdx, 26
	mov	rax, rdx
	shr	rax, 63					; 0000003fH
	add	rdx, rax
; Line 436
	imul	eax, edx, 1000000000			; 3b9aca00H
; Line 715
	mov	QWORD PTR _Tgt$1[rsp], rdx
; Line 99
	sub	ecx, eax
; Line 717
	mov	DWORD PTR _Tgt$1[rsp+8], ecx
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 197
	lea	rcx, QWORD PTR _Tgt$1[rsp]
	call	_Thrd_sleep
; Line 198
	jmp	$LL87@SysSleep
$LN260@SysSleep:
; File D:\Dev\GitHub\vtools\netcpy\System\SysSleep.h
; Line 59
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	mov	rbx, QWORD PTR [rsp+96]
	mov	rbp, QWORD PTR [rsp+104]
	mov	rsi, QWORD PTR [rsp+112]
	movaps	xmm6, XMMWORD PTR [rsp+64]
	add	rsp, 80					; 00000050H
	pop	rdi
	ret	0
?SysSleep@@YAXN@Z ENDP					; SysSleep
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0_Mutex_base@std@@QEAA@H@Z
_TEXT	SEGMENT
this$dead$ = 48
_Flags$dead$ = 56
??0_Mutex_base@std@@QEAA@H@Z PROC			; std::_Mutex_base::_Mutex_base, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\mutex
; Line 64
$LN4:
	sub	rsp, 40					; 00000028H
; Line 65
	mov	edx, 2
	lea	rcx, OFFSET FLAT:?sysmessage@?1??box@SysMessage@@SAAEAV2@XZ@4V2@A
	call	_Mtx_init_in_situ
; Line 66
	lea	rax, OFFSET FLAT:?sysmessage@?1??box@SysMessage@@SAAEAV2@XZ@4V2@A
	add	rsp, 40					; 00000028H
	ret	0
??0_Mutex_base@std@@QEAA@H@Z ENDP			; std::_Mutex_base::_Mutex_base
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??1_Mutex_base@std@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1_Mutex_base@std@@QEAA@XZ PROC			; std::_Mutex_base::~_Mutex_base, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\mutex
; Line 69
	jmp	_Mtx_destroy_in_situ
??1_Mutex_base@std@@QEAA@XZ ENDP			; std::_Mutex_base::~_Mutex_base
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0mutex@std@@QEAA@XZ
_TEXT	SEGMENT
this$dead$ = 48
??0mutex@std@@QEAA@XZ PROC				; std::mutex::mutex, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\mutex
; Line 134
$LN7:
	sub	rsp, 40					; 00000028H
; Line 65
	mov	edx, 2
	lea	rcx, OFFSET FLAT:?sysmessage@?1??box@SysMessage@@SAAEAV2@XZ@4V2@A
	call	_Mtx_init_in_situ
; Line 135
	lea	rax, OFFSET FLAT:?sysmessage@?1??box@SysMessage@@SAAEAV2@XZ@4V2@A
	add	rsp, 40					; 00000028H
	ret	0
??0mutex@std@@QEAA@XZ ENDP				; std::mutex::mutex
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0SysMutex@@QEAA@XZ
_TEXT	SEGMENT
this$dead$ = 48
??0SysMutex@@QEAA@XZ PROC				; SysMutex::SysMutex, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\System\SysMutex.h
; Line 62
$LN9:
	sub	rsp, 40					; 00000028H
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\mutex
; Line 65
	mov	edx, 2
	lea	rcx, OFFSET FLAT:?sysmessage@?1??box@SysMessage@@SAAEAV2@XZ@4V2@A
	call	_Mtx_init_in_situ
; File D:\Dev\GitHub\vtools\netcpy\System\SysMutex.h
; Line 64
	lea	rax, OFFSET FLAT:?sysmessage@?1??box@SysMessage@@SAAEAV2@XZ@4V2@A
	add	rsp, 40					; 00000028H
	ret	0
??0SysMutex@@QEAA@XZ ENDP				; SysMutex::SysMutex
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??1SysMutex@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1SysMutex@@QEAA@XZ PROC				; SysMutex::~SysMutex, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\System\SysMutex.h
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\mutex
; Line 69
	jmp	_Mtx_destroy_in_situ
??1SysMutex@@QEAA@XZ ENDP				; SysMutex::~SysMutex
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??1mutex@std@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1mutex@std@@QEAA@XZ PROC				; std::mutex::~mutex, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\mutex
; Line 69
	jmp	_Mtx_destroy_in_situ
??1mutex@std@@QEAA@XZ ENDP				; std::mutex::~mutex
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??_GSysThread@@UEAAPEAXI@Z
_TEXT	SEGMENT
this$ = 48
__flags$ = 56
??_GSysThread@@UEAAPEAXI@Z PROC				; SysThread::`scalar deleting destructor', COMDAT
$LN16:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
; File D:\Dev\GitHub\vtools\netcpy\System\SysThread.cpp
; Line 61
	lea	rax, OFFSET FLAT:??_7SysThread@@6B@
	mov	ebx, edx
	mov	QWORD PTR [rcx], rax
	mov	rdi, rcx
; Line 63
	call	?stop@SysThread@@QEAAXXZ		; SysThread::stop
; File D:\Dev\GitHub\vtools\netcpy\System\SysMutex.h
; Line 72
	lea	rcx, QWORD PTR [rdi+16]
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\mutex
; Line 69
	call	_Mtx_destroy_in_situ
	test	bl, 1
	je	SHORT $LN12@scalar
	mov	edx, 104				; 00000068H
	mov	rcx, rdi
	call	??3@YAXPEAX_K@Z				; operator delete
$LN12@scalar:
	mov	rbx, QWORD PTR [rsp+48]
	mov	rax, rdi
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
??_GSysThread@@UEAAPEAXI@Z ENDP				; SysThread::`scalar deleting destructor'
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??1SysThread@@UEAA@XZ
_TEXT	SEGMENT
this$ = 48
??1SysThread@@UEAA@XZ PROC				; SysThread::~SysThread, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\System\SysThread.cpp
; Line 61
$LN11:
	push	rbx
	sub	rsp, 32					; 00000020H
	lea	rax, OFFSET FLAT:??_7SysThread@@6B@
	mov	rbx, rcx
	mov	QWORD PTR [rcx], rax
; Line 63
	call	?stop@SysThread@@QEAAXXZ		; SysThread::stop
; File D:\Dev\GitHub\vtools\netcpy\System\SysMutex.h
; Line 72
	lea	rcx, QWORD PTR [rbx+16]
; File D:\Dev\GitHub\vtools\netcpy\System\SysThread.cpp
; Line 64
	add	rsp, 32					; 00000020H
	pop	rbx
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\mutex
; Line 69
	jmp	_Mtx_destroy_in_situ
??1SysThread@@UEAA@XZ ENDP				; SysThread::~SysThread
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?stop@SysThread@@QEAAXXZ
_TEXT	SEGMENT
$T1 = 32
this$ = 64
?stop@SysThread@@QEAAXXZ PROC				; SysThread::stop, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\System\SysThread.cpp
; Line 86
$LN55:
	push	rbx
	sub	rsp, 48					; 00000030H
; Line 87
	cmp	QWORD PTR [rcx+8], 0
	mov	rbx, rcx
	je	SHORT $LN2@stop
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\mutex
; Line 76
	add	rcx, 16
; File D:\Dev\GitHub\vtools\netcpy\System\SysThread.cpp
; Line 87
	mov	QWORD PTR [rsp+64], rdi
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\mutex
; Line 76
	call	_Mtx_lock
	test	eax, eax
	jne	SHORT $LN38@stop
; Line 106
	cmp	DWORD PTR [rbx+92], 2147483647		; 7fffffffH
	je	SHORT $LN51@stop
; Line 95
	lea	rcx, QWORD PTR [rbx+16]
; File D:\Dev\GitHub\vtools\netcpy\System\SysThread.cpp
; Line 91
	mov	BYTE PTR [rbx+96], al
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\mutex
; Line 95
	call	_Mtx_unlock
; File D:\Dev\GitHub\vtools\netcpy\System\SysThread.cpp
; Line 95
	mov	rdi, QWORD PTR [rbx+8]
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 116
	cmp	DWORD PTR [rdi+8], 0
; Line 120
	je	SHORT $LN52@stop
; Line 124
	call	_Thrd_id
	cmp	DWORD PTR [rdi+8], eax
	je	SHORT $LN38@stop
; Line 128
	movups	xmm0, XMMWORD PTR [rdi]
	xor	edx, edx
	lea	rcx, QWORD PTR $T1[rsp]
	movaps	XMMWORD PTR $T1[rsp], xmm0
	call	_Thrd_join
	test	eax, eax
	jne	SHORT $LN53@stop
	xorps	xmm0, xmm0
; Line 132
	movups	XMMWORD PTR [rdi], xmm0
; File D:\Dev\GitHub\vtools\netcpy\System\SysThread.cpp
; Line 98
	mov	rcx, QWORD PTR [rbx+8]
	test	rcx, rcx
	je	SHORT $LN29@stop
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 116
	cmp	DWORD PTR [rcx+8], eax
; Line 92
	jne	SHORT $LN54@stop
	lea	edx, QWORD PTR [rax+16]
	call	??3@YAXPEAX_K@Z				; operator delete
$LN29@stop:
	mov	rdi, QWORD PTR [rsp+64]
; File D:\Dev\GitHub\vtools\netcpy\System\SysThread.cpp
; Line 99
	mov	QWORD PTR [rbx+8], 0
$LN2@stop:
; Line 101
	add	rsp, 48					; 00000030H
	pop	rbx
	ret	0
$LN38@stop:
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 125
	mov	ecx, 5
	call	?_Throw_Cpp_error@std@@YAXH@Z		; std::_Throw_Cpp_error
	int	3
$LN51@stop:
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\mutex
; Line 85
	mov	ecx, 6
; Line 108
	mov	DWORD PTR [rbx+92], 2147483646		; 7ffffffeH
; Line 85
	call	?_Throw_Cpp_error@std@@YAXH@Z		; std::_Throw_Cpp_error
	int	3
$LN52@stop:
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 121
	mov	ecx, 1
	call	?_Throw_Cpp_error@std@@YAXH@Z		; std::_Throw_Cpp_error
	int	3
$LN53@stop:
; Line 129
	mov	ecx, 2
	call	?_Throw_Cpp_error@std@@YAXH@Z		; std::_Throw_Cpp_error
	int	3
$LN54@stop:
; Line 93
	call	?terminate@std@@YAXXZ			; std::terminate
	int	3
$LN49@stop:
?stop@SysThread@@QEAAXXZ ENDP				; SysThread::stop
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??_Gthread@std@@QEAAPEAXI@Z
_TEXT	SEGMENT
this$ = 48
__flags$dead$ = 56
??_Gthread@std@@QEAAPEAXI@Z PROC			; std::thread::`scalar deleting destructor', COMDAT
$LN14:
	push	rbx
	sub	rsp, 32					; 00000020H
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 116
	cmp	DWORD PTR [rcx+8], 0
	mov	rbx, rcx
; Line 92
	jne	SHORT $LN13@scalar
	mov	edx, 16
	call	??3@YAXPEAX_K@Z				; operator delete
	mov	rax, rbx
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
$LN13@scalar:
; Line 93
	call	?terminate@std@@YAXXZ			; std::terminate
	int	3
$LN11@scalar:
??_Gthread@std@@QEAAPEAXI@Z ENDP			; std::thread::`scalar deleting destructor'
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?process@SysThread@@UEAAXXZ
_TEXT	SEGMENT
this$ = 8
?process@SysThread@@UEAAXXZ PROC			; SysThread::process, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\System\SysThread.cpp
; Line 119
	jmp	?SysSleep@@YAXN@Z			; SysSleep
?process@SysThread@@UEAAXXZ ENDP			; SysThread::process
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?count@?$duration@_JU?$ratio@$00$00@std@@@chrono@std@@QEBA_JXZ
_TEXT	SEGMENT
this$ = 8
?count@?$duration@_JU?$ratio@$00$00@std@@@chrono@std@@QEBA_JXZ PROC ; std::chrono::duration<__int64,std::ratio<1,1> >::count, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 110
	mov	rax, QWORD PTR [rcx]
; Line 111
	ret	0
?count@?$duration@_JU?$ratio@$00$00@std@@@chrono@std@@QEBA_JXZ ENDP ; std::chrono::duration<__int64,std::ratio<1,1> >::count
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0_J$0A@@?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@chrono@std@@QEAA@AEB_J@Z
_TEXT	SEGMENT
this$ = 8
_Val$ = 16
??$?0_J$0A@@?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@chrono@std@@QEAA@AEB_J@Z PROC ; std::chrono::duration<__int64,std::ratio<1,10000000> >::duration<__int64,std::ratio<1,10000000> ><__int64,0>, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 99
	mov	rax, QWORD PTR [rdx]
	mov	QWORD PTR [rcx], rax
	mov	rax, rcx
	ret	0
??$?0_J$0A@@?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@chrono@std@@QEAA@AEB_J@Z ENDP ; std::chrono::duration<__int64,std::ratio<1,10000000> >::duration<__int64,std::ratio<1,10000000> ><__int64,0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0_J$0A@@?$duration@_JU?$ratio@$00$00@std@@@chrono@std@@QEAA@AEB_J@Z
_TEXT	SEGMENT
this$ = 8
_Val$ = 16
??$?0_J$0A@@?$duration@_JU?$ratio@$00$00@std@@@chrono@std@@QEAA@AEB_J@Z PROC ; std::chrono::duration<__int64,std::ratio<1,1> >::duration<__int64,std::ratio<1,1> ><__int64,0>, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 99
	mov	rax, QWORD PTR [rdx]
	mov	QWORD PTR [rcx], rax
	mov	rax, rcx
	ret	0
??$?0_J$0A@@?$duration@_JU?$ratio@$00$00@std@@@chrono@std@@QEAA@AEB_J@Z ENDP ; std::chrono::duration<__int64,std::ratio<1,1> >::duration<__int64,std::ratio<1,1> ><__int64,0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$duration_cast@V?$duration@_JU?$ratio@$00$00@std@@@chrono@std@@_JU?$ratio@$00$0DLJKMKAA@@3@$0A@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$00@std@@@01@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 8
_Dur$ = 16
??$duration_cast@V?$duration@_JU?$ratio@$00$00@std@@@chrono@std@@_JU?$ratio@$00$0DLJKMKAA@@3@$0A@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$00@std@@@01@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@@Z PROC ; std::chrono::duration_cast<std::chrono::duration<__int64,std::ratio<1,1> >,__int64,std::ratio<1,1000000000>,0>, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 441
	mov	rax, 1237940039285380275		; 112e0be826d694b3H
	imul	QWORD PTR [rdx]
	sar	rdx, 26
	mov	rax, rdx
	shr	rax, 63					; 0000003fH
	add	rdx, rax
	mov	rax, rcx
; Line 99
	mov	QWORD PTR [rcx], rdx
; Line 448
	ret	0
??$duration_cast@V?$duration@_JU?$ratio@$00$00@std@@@chrono@std@@_JU?$ratio@$00$0DLJKMKAA@@3@$0A@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$00@std@@@01@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@@Z ENDP ; std::chrono::duration_cast<std::chrono::duration<__int64,std::ratio<1,1> >,__int64,std::ratio<1,1000000000>,0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0_J$0A@@?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@std@@QEAA@AEB_J@Z
_TEXT	SEGMENT
this$ = 8
_Val$ = 16
??$?0_J$0A@@?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@std@@QEAA@AEB_J@Z PROC ; std::chrono::duration<__int64,std::ratio<1,1000000> >::duration<__int64,std::ratio<1,1000000> ><__int64,0>, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 99
	mov	rax, QWORD PTR [rdx]
	mov	QWORD PTR [rcx], rax
	mov	rax, rcx
	ret	0
??$?0_J$0A@@?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@std@@QEAA@AEB_J@Z ENDP ; std::chrono::duration<__int64,std::ratio<1,1000000> >::duration<__int64,std::ratio<1,1000000> ><__int64,0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$sleep_for@_JU?$ratio@$00$0PECEA@@std@@@this_thread@std@@YAXAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@1@@Z
_TEXT	SEGMENT
_Tgt$1 = 32
__$ArrayPad$ = 48
_Rel_time$ = 96
??$sleep_for@_JU?$ratio@$00$0PECEA@@std@@@this_thread@std@@YAXAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@1@@Z PROC ; std::this_thread::sleep_for<__int64,std::ratio<1,1000000> >, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 202
$LN268:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rbp
	mov	QWORD PTR [rsp+24], rsi
	push	rdi
	sub	rsp, 80					; 00000050H
	movaps	XMMWORD PTR [rsp+64], xmm6
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
	mov	rsi, rcx
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 670
	call	_Query_perf_frequency
	mov	rbx, rax
; Line 671
	call	_Query_perf_counter
; Line 677
	cmp	rbx, 10000000				; 00989680H
	jne	SHORT $LN9@sleep_for
; Line 680
	imul	rdi, rax, 100				; 00000064H
	jmp	SHORT $LN10@sleep_for
$LN9@sleep_for:
; Line 688
	cdq
	idiv	rbx
	mov	rcx, rax
	imul	rax, rdx, 1000000000			; 3b9aca00H
	cdq
	idiv	rbx
	mov	rdi, rax
	imul	rax, rcx, 1000000000			; 3b9aca00H
; Line 689
	add	rdi, rax
$LN10@sleep_for:
; Line 385
	mov	rax, QWORD PTR [rsi]
	test	rax, rax
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 166
	jle	SHORT $LN258@sleep_for
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 436
	imul	rcx, rax, 1000				; 000003e8H
; Line 99
	mov	rdx, 9223372036854775807		; 7fffffffffffffffH
	mov	rax, rdx
	sub	rax, rcx
; Line 212
	cmp	rdi, rax
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 168
	jge	SHORT $LN5@sleep_for
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 142
	add	rdi, rcx
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 170
	jmp	SHORT $LN258@sleep_for
$LN5@sleep_for:
; Line 171
	mov	rdi, rdx
$LN258@sleep_for:
	movsd	xmm6, QWORD PTR __real@43088e6d68b00000
	mov	rsi, 864000000000000			; 000311cdad160000H
	mov	rbp, 1237940039285380275		; 112e0be826d694b3H
$LL83@sleep_for:
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 670
	call	_Query_perf_frequency
	mov	rbx, rax
; Line 671
	call	_Query_perf_counter
; Line 677
	cmp	rbx, 10000000				; 00989680H
	jne	SHORT $LN89@sleep_for
; Line 680
	imul	rax, rax, 100				; 00000064H
	jmp	SHORT $LN90@sleep_for
$LN89@sleep_for:
; Line 688
	cdq
	idiv	rbx
	mov	rcx, rax
	imul	rax, rdx, 1000000000			; 3b9aca00H
	imul	rcx, rcx, 1000000000			; 3b9aca00H
	cdq
	idiv	rbx
; Line 689
	add	rax, rcx
$LN90@sleep_for:
; Line 212
	cmp	rax, rdi
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 191
	jge	SHORT $LN256@sleep_for
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 212
	mov	rbx, rdi
	sub	rbx, rax
; Line 706
	call	_Xtime_get_ticks
; Line 436
	imul	rdx, rax, 100				; 00000064H
	xorps	xmm0, xmm0
; Line 434
	cvtsi2sd xmm0, rbx
; Line 99
	comisd	xmm0, xmm6
; Line 142
	lea	rcx, QWORD PTR [rdx+rsi]
; Line 708
	ja	SHORT $LN122@sleep_for
; Line 99
	lea	rcx, QWORD PTR [rdx+rbx]
$LN122@sleep_for:
; Line 441
	lea	rax, QWORD PTR [rdx+rbx]
	add	rdx, rsi
	comisd	xmm0, xmm6
	cmovbe	rdx, rax
	mov	rax, rbp
	imul	rdx
	sar	rdx, 26
	mov	rax, rdx
	shr	rax, 63					; 0000003fH
	add	rdx, rax
; Line 436
	imul	eax, edx, 1000000000			; 3b9aca00H
; Line 715
	mov	QWORD PTR _Tgt$1[rsp], rdx
; Line 99
	sub	ecx, eax
; Line 717
	mov	DWORD PTR _Tgt$1[rsp+8], ecx
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 197
	lea	rcx, QWORD PTR _Tgt$1[rsp]
	call	_Thrd_sleep
; Line 198
	jmp	$LL83@sleep_for
$LN256@sleep_for:
; Line 204
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	mov	rbx, QWORD PTR [rsp+96]
	mov	rbp, QWORD PTR [rsp+104]
	mov	rsi, QWORD PTR [rsp+112]
	movaps	xmm6, XMMWORD PTR [rsp+64]
	add	rsp, 80					; 00000050H
	pop	rdi
	ret	0
??$sleep_for@_JU?$ratio@$00$0PECEA@@std@@@this_thread@std@@YAXAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@1@@Z ENDP ; std::this_thread::sleep_for<__int64,std::ratio<1,1000000> >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$_To_absolute_time@_JU?$ratio@$00$0PECEA@@std@@@std@@YA?A_PAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@0@@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 48
_Rel_time$ = 56
??$_To_absolute_time@_JU?$ratio@$00$0PECEA@@std@@@std@@YA?A_PAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@0@@Z PROC ; std::_To_absolute_time<__int64,std::ratio<1,1000000> >, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 162
$LN85:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rsi
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	rsi, rdx
	mov	rbx, rcx
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 670
	call	_Query_perf_frequency
	mov	rdi, rax
; Line 671
	call	_Query_perf_counter
; Line 677
	cmp	rdi, 10000000				; 00989680H
	jne	SHORT $LN7@To_absolut
; Line 680
	imul	rax, rax, 100				; 00000064H
	jmp	SHORT $LN8@To_absolut
$LN7@To_absolut:
; Line 688
	cdq
	idiv	rdi
	mov	rcx, rax
	imul	rax, rdx, 1000000000			; 3b9aca00H
	imul	rcx, rcx, 1000000000			; 3b9aca00H
	cdq
	idiv	rdi
; Line 689
	add	rax, rcx
$LN8@To_absolut:
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 165
	mov	QWORD PTR [rbx], rax
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 385
	mov	rcx, QWORD PTR [rsi]
	test	rcx, rcx
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 166
	jle	SHORT $LN80@To_absolut
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 436
	imul	rdx, rcx, 1000				; 000003e8H
; Line 99
	mov	r8, 9223372036854775807			; 7fffffffffffffffH
	mov	rcx, r8
	sub	rcx, rdx
; Line 212
	cmp	rax, rcx
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 168
	jge	SHORT $LN3@To_absolut
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 142
	lea	rcx, QWORD PTR [rdx+rax]
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 175
	mov	rax, rbx
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 142
	mov	QWORD PTR [rbx], rcx
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 175
	mov	rbx, QWORD PTR [rsp+48]
	mov	rsi, QWORD PTR [rsp+56]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
$LN3@To_absolut:
; Line 171
	mov	QWORD PTR [rbx], r8
$LN80@To_absolut:
; Line 175
	mov	rsi, QWORD PTR [rsp+56]
	mov	rax, rbx
	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
??$_To_absolute_time@_JU?$ratio@$00$0PECEA@@std@@@std@@YA?A_PAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@0@@Z ENDP ; std::_To_absolute_time<__int64,std::ratio<1,1000000> >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??Y?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@QEAAAEAV012@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@@Z
_TEXT	SEGMENT
this$ = 8
_Dur$ = 16
??Y?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@QEAAAEAV012@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@@Z PROC ; std::chrono::time_point<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> > >::operator+=, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 142
	mov	rax, QWORD PTR [rdx]
	add	QWORD PTR [rcx], rax
; Line 234
	mov	rax, rcx
; Line 235
	ret	0
??Y?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@QEAAAEAV012@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@@Z ENDP ; std::chrono::time_point<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> > >::operator+=
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?count@?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@chrono@std@@QEBA_JXZ
_TEXT	SEGMENT
this$ = 8
?count@?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@chrono@std@@QEBA_JXZ PROC ; std::chrono::duration<__int64,std::ratio<1,10000000> >::count, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 110
	mov	rax, QWORD PTR [rcx]
; Line 111
	ret	0
?count@?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@chrono@std@@QEBA_JXZ ENDP ; std::chrono::duration<__int64,std::ratio<1,10000000> >::count
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??Y?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAAAEAV012@AEBV012@@Z
_TEXT	SEGMENT
this$ = 8
_Right$ = 16
??Y?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAAAEAV012@AEBV012@@Z PROC ; std::chrono::duration<__int64,std::ratio<1,1000000000> >::operator+=, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 142
	mov	rax, QWORD PTR [rdx]
	add	QWORD PTR [rcx], rax
; Line 143
	mov	rax, rcx
; Line 144
	ret	0
??Y?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAAAEAV012@AEBV012@@Z ENDP ; std::chrono::duration<__int64,std::ratio<1,1000000000> >::operator+=
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?O_JU?$ratio@$00$0PECEA@@std@@_JU01@@chrono@std@@YA_NAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@0@Z
_TEXT	SEGMENT
_Left$ = 8
_Right$ = 16
??$?O_JU?$ratio@$00$0PECEA@@std@@_JU01@@chrono@std@@YA_NAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@0@Z PROC ; std::chrono::operator><__int64,std::ratio<1,1000000>,__int64,std::ratio<1,1000000> >, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 385
	mov	rax, QWORD PTR [rcx]
	cmp	QWORD PTR [rdx], rax
	setl	al
; Line 400
	ret	0
??$?O_JU?$ratio@$00$0PECEA@@std@@_JU01@@chrono@std@@YA_NAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@0@Z ENDP ; std::chrono::operator><__int64,std::ratio<1,1000000>,__int64,std::ratio<1,1000000> >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?GUsteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@_JU?$ratio@$00$0PECEA@@2@@chrono@std@@YA?AV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@01@AEBV201@AEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 8
_Left$ = 16
_Right$ = 24
??$?GUsteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@_JU?$ratio@$00$0PECEA@@2@@chrono@std@@YA?AV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@01@AEBV201@AEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@@Z PROC ; std::chrono::operator-<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> >,__int64,std::ratio<1,1000000> >, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 436
	imul	rax, QWORD PTR [r8], -1000		; fffffffffffffc18H
; Line 292
	add	rax, QWORD PTR [rdx]
; Line 204
	mov	QWORD PTR [rcx], rax
; Line 543
	mov	rax, rcx
; Line 544
	ret	0
??$?GUsteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@_JU?$ratio@$00$0PECEA@@2@@chrono@std@@YA?AV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@01@AEBV201@AEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@@Z ENDP ; std::chrono::operator-<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> >,__int64,std::ratio<1,1000000> >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?MUsteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@V312@@chrono@std@@YA_NAEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@01@0@Z
_TEXT	SEGMENT
_Left$ = 8
_Right$ = 16
??$?MUsteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@V312@@chrono@std@@YA_NAEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@01@0@Z PROC ; std::chrono::operator<<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> >,std::chrono::duration<__int64,std::ratio<1,1000000000> > >, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 385
	mov	rax, QWORD PTR [rdx]
	cmp	QWORD PTR [rcx], rax
	setl	al
; Line 574
	ret	0
??$?MUsteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@V312@@chrono@std@@YA_NAEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@01@0@Z ENDP ; std::chrono::operator<<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> >,std::chrono::duration<__int64,std::ratio<1,1000000000> > >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0_JU?$ratio@$00$0PECEA@@std@@$0A@@?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@12@@Z
_TEXT	SEGMENT
this$ = 8
_Dur$ = 16
??$?0_JU?$ratio@$00$0PECEA@@std@@$0A@@?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@12@@Z PROC ; std::chrono::duration<__int64,std::ratio<1,1000000000> >::duration<__int64,std::ratio<1,1000000000> ><__int64,std::ratio<1,1000000>,0>, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 436
	imul	rax, QWORD PTR [rdx], 1000		; 000003e8H
; Line 107
	mov	QWORD PTR [rcx], rax
	mov	rax, rcx
	ret	0
??$?0_JU?$ratio@$00$0PECEA@@std@@$0A@@?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@12@@Z ENDP ; std::chrono::duration<__int64,std::ratio<1,1000000000> >::duration<__int64,std::ratio<1,1000000000> ><__int64,std::ratio<1,1000000>,0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$sleep_until@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@this_thread@std@@YAXAEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@1@@Z
_TEXT	SEGMENT
_Tgt$1 = 32
__$ArrayPad$ = 48
_Abs_time$ = 96
??$sleep_until@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@this_thread@std@@YAXAEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@1@@Z PROC ; std::this_thread::sleep_until<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> > >, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 185
$LN182:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rbp
	mov	QWORD PTR [rsp+24], rsi
	push	rdi
	sub	rsp, 80					; 00000050H
	movaps	XMMWORD PTR [rsp+64], xmm6
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
	movsd	xmm6, QWORD PTR __real@43088e6d68b00000
	mov	rdi, rcx
	mov	rsi, 864000000000000			; 000311cdad160000H
	mov	rbp, 1237940039285380275		; 112e0be826d694b3H
$LL2@sleep_unti:
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 670
	call	_Query_perf_frequency
	mov	rbx, rax
; Line 671
	call	_Query_perf_counter
; Line 677
	cmp	rbx, 10000000				; 00989680H
	jne	SHORT $LN8@sleep_unti
; Line 680
	imul	rax, rax, 100				; 00000064H
	jmp	SHORT $LN9@sleep_unti
$LN8@sleep_unti:
; Line 688
	cdq
	idiv	rbx
	mov	rcx, rax
	imul	rax, rdx, 1000000000			; 3b9aca00H
	imul	rcx, rcx, 1000000000			; 3b9aca00H
	cdq
	idiv	rbx
; Line 689
	add	rax, rcx
$LN9@sleep_unti:
; Line 212
	mov	rbx, QWORD PTR [rdi]
	cmp	rax, rbx
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 191
	jge	SHORT $LN175@sleep_unti
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 212
	sub	rbx, rax
; Line 706
	call	_Xtime_get_ticks
; Line 436
	imul	rdx, rax, 100				; 00000064H
	xorps	xmm0, xmm0
; Line 434
	cvtsi2sd xmm0, rbx
; Line 99
	comisd	xmm0, xmm6
; Line 142
	lea	rcx, QWORD PTR [rdx+rsi]
; Line 708
	ja	SHORT $LN41@sleep_unti
; Line 99
	lea	rcx, QWORD PTR [rdx+rbx]
$LN41@sleep_unti:
; Line 441
	lea	rax, QWORD PTR [rdx+rbx]
	add	rdx, rsi
	comisd	xmm0, xmm6
	cmovbe	rdx, rax
	mov	rax, rbp
	imul	rdx
	sar	rdx, 26
	mov	rax, rdx
	shr	rax, 63					; 0000003fH
	add	rdx, rax
; Line 436
	imul	eax, edx, 1000000000			; 3b9aca00H
; Line 715
	mov	QWORD PTR _Tgt$1[rsp], rdx
; Line 99
	sub	ecx, eax
; Line 717
	mov	DWORD PTR _Tgt$1[rsp+8], ecx
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\thread
; Line 197
	lea	rcx, QWORD PTR _Tgt$1[rsp]
	call	_Thrd_sleep
; Line 198
	jmp	$LL2@sleep_unti
$LN175@sleep_unti:
; Line 199
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	mov	rbx, QWORD PTR [rsp+96]
	mov	rbp, QWORD PTR [rsp+104]
	mov	rsi, QWORD PTR [rsp+112]
	movaps	xmm6, XMMWORD PTR [rsp+64]
	add	rsp, 80					; 00000050H
	pop	rdi
	ret	0
??$sleep_until@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@this_thread@std@@YAXAEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@1@@Z ENDP ; std::this_thread::sleep_until<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> > >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?M_JU?$ratio@$00$0PECEA@@std@@_JU01@@chrono@std@@YA_NAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@0@Z
_TEXT	SEGMENT
_Left$ = 8
_Right$ = 16
??$?M_JU?$ratio@$00$0PECEA@@std@@_JU01@@chrono@std@@YA_NAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@0@Z PROC ; std::chrono::operator<<__int64,std::ratio<1,1000000>,__int64,std::ratio<1,1000000> >, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 385
	mov	rax, QWORD PTR [rdx]
	cmp	QWORD PTR [rcx], rax
	setl	al
; Line 386
	ret	0
??$?M_JU?$ratio@$00$0PECEA@@std@@_JU01@@chrono@std@@YA_NAEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@0@Z ENDP ; std::chrono::operator<<__int64,std::ratio<1,1000000>,__int64,std::ratio<1,1000000> >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?G_JU?$ratio@$00$0DLJKMKAA@@std@@_JU?$ratio@$00$0PECEA@@1@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV201@AEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 8
_Left$ = 16
_Right$ = 24
??$?G_JU?$ratio@$00$0DLJKMKAA@@std@@_JU?$ratio@$00$0PECEA@@1@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV201@AEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@@Z PROC ; std::chrono::operator-<__int64,std::ratio<1,1000000000>,__int64,std::ratio<1,1000000> >, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 436
	imul	rax, QWORD PTR [r8], 1000		; 000003e8H
; Line 292
	mov	rdx, QWORD PTR [rdx]
	sub	rdx, rax
	mov	rax, rcx
; Line 99
	mov	QWORD PTR [rcx], rdx
; Line 293
	ret	0
??$?G_JU?$ratio@$00$0DLJKMKAA@@std@@_JU?$ratio@$00$0PECEA@@1@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV201@AEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@@Z ENDP ; std::chrono::operator-<__int64,std::ratio<1,1000000000>,__int64,std::ratio<1,1000000> >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?M_JU?$ratio@$00$0DLJKMKAA@@std@@_JU01@@chrono@std@@YA_NAEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@0@Z
_TEXT	SEGMENT
_Left$ = 8
_Right$ = 16
??$?M_JU?$ratio@$00$0DLJKMKAA@@std@@_JU01@@chrono@std@@YA_NAEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@0@Z PROC ; std::chrono::operator<<__int64,std::ratio<1,1000000000>,__int64,std::ratio<1,1000000000> >, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 385
	mov	rax, QWORD PTR [rdx]
	cmp	QWORD PTR [rcx], rax
	setl	al
; Line 386
	ret	0
??$?M_JU?$ratio@$00$0DLJKMKAA@@std@@_JU01@@chrono@std@@YA_NAEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@0@Z ENDP ; std::chrono::operator<<__int64,std::ratio<1,1000000000>,__int64,std::ratio<1,1000000000> >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$duration_cast@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@_JU?$ratio@$00$0PECEA@@3@$0A@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 8
_Dur$ = 16
??$duration_cast@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@_JU?$ratio@$00$0PECEA@@3@$0A@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@@Z PROC ; std::chrono::duration_cast<std::chrono::duration<__int64,std::ratio<1,1000000000> >,__int64,std::ratio<1,1000000>,0>, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 436
	imul	rax, QWORD PTR [rdx], 1000		; 000003e8H
; Line 99
	mov	QWORD PTR [rcx], rax
; Line 436
	mov	rax, rcx
; Line 448
	ret	0
??$duration_cast@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@_JU?$ratio@$00$0PECEA@@3@$0A@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@_JU?$ratio@$00$0PECEA@@std@@@01@@Z ENDP ; std::chrono::duration_cast<std::chrono::duration<__int64,std::ratio<1,1000000000> >,__int64,std::ratio<1,1000000>,0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?NUsteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@V312@@chrono@std@@YA_NAEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@01@0@Z
_TEXT	SEGMENT
_Left$ = 8
_Right$ = 16
??$?NUsteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@V312@@chrono@std@@YA_NAEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@01@0@Z PROC ; std::chrono::operator<=<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> >,std::chrono::duration<__int64,std::ratio<1,1000000000> > >, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 580
	mov	rax, QWORD PTR [rcx]
	cmp	QWORD PTR [rdx], rax
	setge	al
; Line 581
	ret	0
??$?NUsteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@V312@@chrono@std@@YA_NAEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@01@0@Z ENDP ; std::chrono::operator<=<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> >,std::chrono::duration<__int64,std::ratio<1,1000000000> > >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$_To_timespec64_sys_10_day_clamped@_JU?$ratio@$00$0DLJKMKAA@@std@@@std@@YA_NAEAU_timespec64@@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@0@@Z
_TEXT	SEGMENT
_Ts64$ = 48
_Rel_time$ = 56
??$_To_timespec64_sys_10_day_clamped@_JU?$ratio@$00$0DLJKMKAA@@std@@@std@@YA_NAEAU_timespec64@@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@0@@Z PROC ; std::_To_timespec64_sys_10_day_clamped<__int64,std::ratio<1,1000000000> >, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 699
$LN137:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	rbx, rdx
	mov	rdi, rcx
; Line 706
	call	_Xtime_get_ticks
; Line 436
	imul	rdx, rax, 100				; 00000064H
	xorps	xmm0, xmm0
; Line 434
	mov	rax, QWORD PTR [rbx]
; Line 708
	mov	r8, 864000000000000			; 000311cdad160000H
; Line 434
	cvtsi2sd xmm0, rax
; Line 142
	lea	rcx, QWORD PTR [rdx+r8]
; Line 99
	comisd	xmm0, QWORD PTR __real@43088e6d68b00000
; Line 385
	seta	r9b
; Line 708
	test	r9b, r9b
	jne	SHORT $LN3@To_timespe
; Line 99
	lea	rcx, QWORD PTR [rax+rdx]
$LN3@To_timespe:
; Line 719
	mov	rbx, QWORD PTR [rsp+48]
; Line 441
	add	rax, rdx
	add	rdx, r8
	test	r9b, r9b
	cmove	rdx, rax
	mov	rax, 1237940039285380275		; 112e0be826d694b3H
	imul	rdx
; Line 718
	movzx	eax, r9b
; Line 441
	sar	rdx, 26
	mov	r8, rdx
	shr	r8, 63					; 0000003fH
	add	rdx, r8
; Line 436
	imul	r8d, edx, 1000000000			; 3b9aca00H
; Line 715
	mov	QWORD PTR [rdi], rdx
; Line 99
	sub	ecx, r8d
; Line 717
	mov	DWORD PTR [rdi+8], ecx
; Line 719
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
??$_To_timespec64_sys_10_day_clamped@_JU?$ratio@$00$0DLJKMKAA@@std@@@std@@YA_NAEAU_timespec64@@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@0@@Z ENDP ; std::_To_timespec64_sys_10_day_clamped<__int64,std::ratio<1,1000000000> >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?count@?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@std@@QEBA_JXZ
_TEXT	SEGMENT
this$ = 8
?count@?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@std@@QEBA_JXZ PROC ; std::chrono::duration<__int64,std::ratio<1,1000000> >::count, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 110
	mov	rax, QWORD PTR [rcx]
; Line 111
	ret	0
?count@?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@std@@QEBA_JXZ ENDP ; std::chrono::duration<__int64,std::ratio<1,1000000> >::count
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??Z?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAAAEAV012@AEBV012@@Z
_TEXT	SEGMENT
this$ = 8
_Right$ = 16
??Z?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAAAEAV012@AEBV012@@Z PROC ; std::chrono::duration<__int64,std::ratio<1,1000000000> >::operator-=, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 147
	mov	rax, QWORD PTR [rdx]
	sub	QWORD PTR [rcx], rax
; Line 148
	mov	rax, rcx
; Line 149
	ret	0
??Z?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAAAEAV012@AEBV012@@Z ENDP ; std::chrono::duration<__int64,std::ratio<1,1000000000> >::operator-=
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0_JU?$ratio@$00$00@std@@$0A@@?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@_JU?$ratio@$00$00@std@@@12@@Z
_TEXT	SEGMENT
this$ = 8
_Dur$ = 16
??$?0_JU?$ratio@$00$00@std@@$0A@@?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@_JU?$ratio@$00$00@std@@@12@@Z PROC ; std::chrono::duration<__int64,std::ratio<1,1000000000> >::duration<__int64,std::ratio<1,1000000000> ><__int64,std::ratio<1,1>,0>, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 436
	imul	rax, QWORD PTR [rdx], 1000000000	; 3b9aca00H
; Line 107
	mov	QWORD PTR [rcx], rax
	mov	rax, rcx
	ret	0
??$?0_JU?$ratio@$00$00@std@@$0A@@?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@_JU?$ratio@$00$00@std@@@12@@Z ENDP ; std::chrono::duration<__int64,std::ratio<1,1000000000> >::duration<__int64,std::ratio<1,1000000000> ><__int64,std::ratio<1,1>,0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0_JU?$ratio@$00$0JIJGIA@@std@@$0A@@?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@12@@Z
_TEXT	SEGMENT
this$ = 8
_Dur$ = 16
??$?0_JU?$ratio@$00$0JIJGIA@@std@@$0A@@?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@12@@Z PROC ; std::chrono::duration<__int64,std::ratio<1,1000000000> >::duration<__int64,std::ratio<1,1000000000> ><__int64,std::ratio<1,10000000>,0>, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 436
	imul	rax, QWORD PTR [rdx], 100		; 00000064H
; Line 107
	mov	QWORD PTR [rcx], rax
	mov	rax, rcx
	ret	0
??$?0_JU?$ratio@$00$0JIJGIA@@std@@$0A@@?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@12@@Z ENDP ; std::chrono::duration<__int64,std::ratio<1,1000000000> >::duration<__int64,std::ratio<1,1000000000> ><__int64,std::ratio<1,10000000>,0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?MNU?$ratio@$00$00@std@@_JU?$ratio@$00$0DLJKMKAA@@1@@chrono@std@@YA_NAEBV?$duration@NU?$ratio@$00$00@std@@@01@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@@Z
_TEXT	SEGMENT
_Left$ = 8
_Right$ = 16
??$?MNU?$ratio@$00$00@std@@_JU?$ratio@$00$0DLJKMKAA@@1@@chrono@std@@YA_NAEBV?$duration@NU?$ratio@$00$00@std@@@01@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@@Z PROC ; std::chrono::operator<<double,std::ratio<1,1>,__int64,std::ratio<1,1000000000> >, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 436
	movsd	xmm1, QWORD PTR [rcx]
	xorps	xmm0, xmm0
	mulsd	xmm1, QWORD PTR __real@41cdcd6500000000
; Line 434
	cvtsi2sd xmm0, QWORD PTR [rdx]
; Line 385
	comisd	xmm0, xmm1
	seta	al
; Line 386
	ret	0
??$?MNU?$ratio@$00$00@std@@_JU?$ratio@$00$0DLJKMKAA@@1@@chrono@std@@YA_NAEBV?$duration@NU?$ratio@$00$00@std@@@01@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@@Z ENDP ; std::chrono::operator<<double,std::ratio<1,1>,__int64,std::ratio<1,1000000000> >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?count@?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEBANXZ
_TEXT	SEGMENT
this$ = 8
?count@?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEBANXZ PROC ; std::chrono::duration<double,std::ratio<1,1000000000> >::count, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 110
	movsd	xmm0, QWORD PTR [rcx]
; Line 111
	ret	0
?count@?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEBANXZ ENDP ; std::chrono::duration<double,std::ratio<1,1000000000> >::count
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$duration_cast@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@_JU?$ratio@$00$00@3@$0A@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@_JU?$ratio@$00$00@std@@@01@@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 8
_Dur$ = 16
??$duration_cast@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@_JU?$ratio@$00$00@3@$0A@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@_JU?$ratio@$00$00@std@@@01@@Z PROC ; std::chrono::duration_cast<std::chrono::duration<__int64,std::ratio<1,1000000000> >,__int64,std::ratio<1,1>,0>, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 436
	imul	rax, QWORD PTR [rdx], 1000000000	; 3b9aca00H
; Line 99
	mov	QWORD PTR [rcx], rax
; Line 436
	mov	rax, rcx
; Line 448
	ret	0
??$duration_cast@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@_JU?$ratio@$00$00@3@$0A@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@_JU?$ratio@$00$00@std@@@01@@Z ENDP ; std::chrono::duration_cast<std::chrono::duration<__int64,std::ratio<1,1000000000> >,__int64,std::ratio<1,1>,0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$duration_cast@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@_JU?$ratio@$00$0JIJGIA@@3@$0A@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@01@@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 8
_Dur$ = 16
??$duration_cast@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@_JU?$ratio@$00$0JIJGIA@@3@$0A@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@01@@Z PROC ; std::chrono::duration_cast<std::chrono::duration<__int64,std::ratio<1,1000000000> >,__int64,std::ratio<1,10000000>,0>, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 436
	imul	rax, QWORD PTR [rdx], 100		; 00000064H
; Line 99
	mov	QWORD PTR [rcx], rax
; Line 436
	mov	rax, rcx
; Line 448
	ret	0
??$duration_cast@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@_JU?$ratio@$00$0JIJGIA@@3@$0A@@chrono@std@@YA?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@01@@Z ENDP ; std::chrono::duration_cast<std::chrono::duration<__int64,std::ratio<1,1000000000> >,__int64,std::ratio<1,10000000>,0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0NU?$ratio@$00$00@std@@$0A@@?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@NU?$ratio@$00$00@std@@@12@@Z
_TEXT	SEGMENT
this$ = 8
_Dur$ = 16
??$?0NU?$ratio@$00$00@std@@$0A@@?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@NU?$ratio@$00$00@std@@@12@@Z PROC ; std::chrono::duration<double,std::ratio<1,1000000000> >::duration<double,std::ratio<1,1000000000> ><double,std::ratio<1,1>,0>, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 436
	movsd	xmm0, QWORD PTR [rdx]
; Line 107
	mov	rax, rcx
; Line 436
	mulsd	xmm0, QWORD PTR __real@41cdcd6500000000
; Line 107
	movsd	QWORD PTR [rcx], xmm0
	ret	0
??$?0NU?$ratio@$00$00@std@@$0A@@?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@NU?$ratio@$00$00@std@@@12@@Z ENDP ; std::chrono::duration<double,std::ratio<1,1000000000> >::duration<double,std::ratio<1,1000000000> ><double,std::ratio<1,1>,0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0_JU?$ratio@$00$0DLJKMKAA@@std@@$0A@@?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@@Z
_TEXT	SEGMENT
this$ = 8
_Dur$ = 16
??$?0_JU?$ratio@$00$0DLJKMKAA@@std@@$0A@@?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@@Z PROC ; std::chrono::duration<double,std::ratio<1,1000000000> >::duration<double,std::ratio<1,1000000000> ><__int64,std::ratio<1,1000000000>,0>, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 107
	xorps	xmm0, xmm0
	mov	rax, rcx
; Line 434
	cvtsi2sd xmm0, QWORD PTR [rdx]
; Line 107
	movsd	QWORD PTR [rcx], xmm0
	ret	0
??$?0_JU?$ratio@$00$0DLJKMKAA@@std@@$0A@@?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@@Z ENDP ; std::chrono::duration<double,std::ratio<1,1000000000> >::duration<double,std::ratio<1,1000000000> ><__int64,std::ratio<1,1000000000>,0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$duration_cast@V?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@NU?$ratio@$00$00@3@$0A@@chrono@std@@YA?AV?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@NU?$ratio@$00$00@std@@@01@@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 8
_Dur$ = 16
??$duration_cast@V?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@NU?$ratio@$00$00@3@$0A@@chrono@std@@YA?AV?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@NU?$ratio@$00$00@std@@@01@@Z PROC ; std::chrono::duration_cast<std::chrono::duration<double,std::ratio<1,1000000000> >,double,std::ratio<1,1>,0>, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 436
	movsd	xmm0, QWORD PTR [rdx]
	mov	rax, rcx
	mulsd	xmm0, QWORD PTR __real@41cdcd6500000000
; Line 99
	movsd	QWORD PTR [rcx], xmm0
; Line 448
	ret	0
??$duration_cast@V?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@NU?$ratio@$00$00@3@$0A@@chrono@std@@YA?AV?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@NU?$ratio@$00$00@std@@@01@@Z ENDP ; std::chrono::duration_cast<std::chrono::duration<double,std::ratio<1,1000000000> >,double,std::ratio<1,1>,0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$duration_cast@V?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@_JU?$ratio@$00$0DLJKMKAA@@3@$0A@@chrono@std@@YA?AV?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 8
_Dur$ = 16
??$duration_cast@V?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@_JU?$ratio@$00$0DLJKMKAA@@3@$0A@@chrono@std@@YA?AV?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@@Z PROC ; std::chrono::duration_cast<std::chrono::duration<double,std::ratio<1,1000000000> >,__int64,std::ratio<1,1000000000>,0>, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 422
	xorps	xmm0, xmm0
; Line 434
	mov	rax, rcx
	cvtsi2sd xmm0, QWORD PTR [rdx]
; Line 99
	movsd	QWORD PTR [rcx], xmm0
; Line 448
	ret	0
??$duration_cast@V?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@_JU?$ratio@$00$0DLJKMKAA@@3@$0A@@chrono@std@@YA?AV?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@01@AEBV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@01@@Z ENDP ; std::chrono::duration_cast<std::chrono::duration<double,std::ratio<1,1000000000> >,__int64,std::ratio<1,1000000000>,0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0N$0A@@?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBN@Z
_TEXT	SEGMENT
this$ = 8
_Val$ = 16
??$?0N$0A@@?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBN@Z PROC ; std::chrono::duration<double,std::ratio<1,1000000000> >::duration<double,std::ratio<1,1000000000> ><double,0>, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\__msvc_chrono.hpp
; Line 99
	mov	rax, QWORD PTR [rdx]
	mov	QWORD PTR [rcx], rax
	mov	rax, rcx
	ret	0
??$?0N$0A@@?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@QEAA@AEBN@Z ENDP ; std::chrono::duration<double,std::ratio<1,1000000000> >::duration<double,std::ratio<1,1000000000> ><double,0>
_TEXT	ENDS
END
