; Listing generated by Microsoft (R) Optimizing Compiler Version 19.37.32822.0 

include listing.inc

INCLUDELIB OLDNAMES

EXTRN	__imp_accept:PROC
EXTRN	__imp_bind:PROC
EXTRN	__imp_closesocket:PROC
EXTRN	__imp_listen:PROC
EXTRN	__imp_send:PROC
EXTRN	__imp_socket:PROC
EXTRN	__imp_connect:PROC
EXTRN	__imp_recv:PROC
EXTRN	__imp_htonl:PROC
EXTRN	__imp_htons:PROC
EXTRN	__imp_ioctlsocket:PROC
EXTRN	__imp_setsockopt:PROC
PUBLIC	?getAddress@IPAddress@@QEBA?AUin_addr@@XZ	; IPAddress::getAddress
PUBLIC	?setAddress@IPAddress@@QEAAXUin_addr@@@Z	; IPAddress::setAddress
PUBLIC	?receiveData@TCPSocket@@QEAA_NPEAD_K@Z		; TCPSocket::receiveData
PUBLIC	?sendData@TCPSocket@@QEAA_NPEBD_K@Z		; TCPSocket::sendData
PUBLIC	?connectSocket@TCPSocket@@QEAA_NAEAVIPAddress@@G@Z ; TCPSocket::connectSocket
PUBLIC	?acceptConnection@TCPSocket@@QEAA_NAEAV1@AEAVIPAddress@@@Z ; TCPSocket::acceptConnection
PUBLIC	?listenPort@TCPSocket@@QEAA_NXZ			; TCPSocket::listenPort
PUBLIC	?bindSocket@TCPSocket@@QEAA_NG@Z		; TCPSocket::bindSocket
PUBLIC	?closeSocket@TCPSocket@@QEAAXXZ			; TCPSocket::closeSocket
PUBLIC	?createSocket@TCPSocket@@QEAA_N_N@Z		; TCPSocket::createSocket
PUBLIC	??1TCPSocket@@QEAA@XZ				; TCPSocket::~TCPSocket
PUBLIC	??0TCPSocket@@QEAA@XZ				; TCPSocket::TCPSocket
;	COMDAT pdata
pdata	SEGMENT
$pdata$?receiveData@TCPSocket@@QEAA_NPEAD_K@Z DD imagerel $LN22
	DD	imagerel $LN22+112
	DD	imagerel $unwind$?receiveData@TCPSocket@@QEAA_NPEAD_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?sendData@TCPSocket@@QEAA_NPEBD_K@Z DD imagerel $LN22
	DD	imagerel $LN22+112
	DD	imagerel $unwind$?sendData@TCPSocket@@QEAA_NPEBD_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?connectSocket@TCPSocket@@QEAA_NAEAVIPAddress@@G@Z DD imagerel $LN11
	DD	imagerel $LN11+130
	DD	imagerel $unwind$?connectSocket@TCPSocket@@QEAA_NAEAVIPAddress@@G@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?acceptConnection@TCPSocket@@QEAA_NAEAV1@AEAVIPAddress@@@Z DD imagerel $LN14
	DD	imagerel $LN14+141
	DD	imagerel $unwind$?acceptConnection@TCPSocket@@QEAA_NAEAV1@AEAVIPAddress@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?listenPort@TCPSocket@@QEAA_NXZ DD imagerel $LN8
	DD	imagerel $LN8+41
	DD	imagerel $unwind$?listenPort@TCPSocket@@QEAA_NXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?bindSocket@TCPSocket@@QEAA_NG@Z DD imagerel $LN9
	DD	imagerel $LN9+140
	DD	imagerel $unwind$?bindSocket@TCPSocket@@QEAA_NG@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?closeSocket@TCPSocket@@QEAAXXZ DD imagerel $LN7
	DD	imagerel $LN7+37
	DD	imagerel $unwind$?closeSocket@TCPSocket@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?createSocket@TCPSocket@@QEAA_N_N@Z DD imagerel $LN16
	DD	imagerel $LN16+184
	DD	imagerel $unwind$?createSocket@TCPSocket@@QEAA_N_N@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1TCPSocket@@QEAA@XZ DD imagerel $LN9
	DD	imagerel $LN9+37
	DD	imagerel $unwind$??1TCPSocket@@QEAA@XZ
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1TCPSocket@@QEAA@XZ DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?createSocket@TCPSocket@@QEAA_N_N@Z DD 021519H
	DD	030027206H
	DD	imagerel __GSHandlerCheck
	DD	038H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?closeSocket@TCPSocket@@QEAAXXZ DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?bindSocket@TCPSocket@@QEAA_NG@Z DD 021519H
	DD	030027206H
	DD	imagerel __GSHandlerCheck
	DD	030H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?listenPort@TCPSocket@@QEAA_NXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?acceptConnection@TCPSocket@@QEAA_NAEAV1@AEAVIPAddress@@@Z DD 041719H
	DD	070047208H
	DD	030026003H
	DD	imagerel __GSHandlerCheck
	DD	038H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?connectSocket@TCPSocket@@QEAA_NAEAVIPAddress@@G@Z DD 041919H
	DD	0d340aH
	DD	07006720aH
	DD	imagerel __GSHandlerCheck
	DD	030H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?sendData@TCPSocket@@QEAA_NPEBD_K@Z DD 081501H
	DD	087415H
	DD	076415H
	DD	063415H
	DD	0e0113215H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?receiveData@TCPSocket@@QEAA_NPEAD_K@Z DD 081501H
	DD	087415H
	DD	076415H
	DD	063415H
	DD	0e0113215H
; Function compile flags: /Ogtpy
;	COMDAT ??0TCPSocket@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0TCPSocket@@QEAA@XZ PROC				; TCPSocket::TCPSocket, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\Network\TCPSocket.cpp
; Line 49
	mov	QWORD PTR [rcx], -1
; Line 52
	mov	rax, rcx
	ret	0
??0TCPSocket@@QEAA@XZ ENDP				; TCPSocket::TCPSocket
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??1TCPSocket@@QEAA@XZ
_TEXT	SEGMENT
this$ = 48
??1TCPSocket@@QEAA@XZ PROC				; TCPSocket::~TCPSocket, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\Network\TCPSocket.cpp
; Line 58
$LN9:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
; Line 126
	mov	rcx, QWORD PTR [rcx]
	cmp	rcx, -1
	je	SHORT $LN6@TCPSocket
; Line 129
	call	QWORD PTR __imp_closesocket
$LN6@TCPSocket:
; Line 60
	mov	QWORD PTR [rbx], -1
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
??1TCPSocket@@QEAA@XZ ENDP				; TCPSocket::~TCPSocket
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?createSocket@TCPSocket@@QEAA_N_N@Z
_TEXT	SEGMENT
optval$ = 48
blockMode$ = 52
__$ArrayPad$ = 56
this$ = 80
blocking$dead$ = 88
?createSocket@TCPSocket@@QEAA_N_N@Z PROC		; TCPSocket::createSocket, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\Network\TCPSocket.cpp
; Line 67
$LN16:
	push	rbx
	sub	rsp, 64					; 00000040H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
	mov	rbx, rcx
; Line 126
	mov	rcx, QWORD PTR [rcx]
	cmp	rcx, -1
	je	SHORT $LN7@createSock
; Line 129
	call	QWORD PTR __imp_closesocket
$LN7@createSock:
; Line 77
	mov	edx, 1
; Line 135
	mov	QWORD PTR [rbx], -1
; Line 77
	lea	ecx, QWORD PTR [rdx+1]
	lea	r8d, QWORD PTR [rdx+5]
	call	QWORD PTR __imp_socket
	mov	QWORD PTR [rbx], rax
; Line 78
	cmp	rax, -1
	je	SHORT $LN9@createSock
; Line 87
	mov	edx, 6
	mov	DWORD PTR optval$[rsp], 1
	lea	r9, QWORD PTR optval$[rsp]
	mov	DWORD PTR [rsp+32], 4
	mov	rcx, rax
	lea	r8d, QWORD PTR [rdx-5]
	call	QWORD PTR __imp_setsockopt
	test	eax, eax
	jne	SHORT $LN9@createSock
; Line 97
	mov	rcx, QWORD PTR [rbx]
	lea	r8, QWORD PTR blockMode$[rsp]
	mov	edx, -2147195266			; ffffffff8004667eH
	mov	DWORD PTR blockMode$[rsp], eax
	call	QWORD PTR __imp_ioctlsocket
	test	eax, eax
	sete	al
; Line 119
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 64					; 00000040H
	pop	rbx
	ret	0
$LN9@createSock:
; Line 100
	xor	al, al
; Line 119
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 64					; 00000040H
	pop	rbx
	ret	0
?createSocket@TCPSocket@@QEAA_N_N@Z ENDP		; TCPSocket::createSocket
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?closeSocket@TCPSocket@@QEAAXXZ
_TEXT	SEGMENT
this$ = 48
?closeSocket@TCPSocket@@QEAAXXZ PROC			; TCPSocket::closeSocket, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\Network\TCPSocket.cpp
; Line 125
$LN7:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
; Line 126
	mov	rcx, QWORD PTR [rcx]
	cmp	rcx, -1
	je	SHORT $LN4@closeSocke
; Line 129
	call	QWORD PTR __imp_closesocket
$LN4@closeSocke:
; Line 136
	mov	QWORD PTR [rbx], -1
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
?closeSocket@TCPSocket@@QEAAXXZ ENDP			; TCPSocket::closeSocket
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?bindSocket@TCPSocket@@QEAA_NG@Z
_TEXT	SEGMENT
addr4$ = 32
__$ArrayPad$ = 48
this$ = 80
port$ = 88
?bindSocket@TCPSocket@@QEAA_NG@Z PROC			; TCPSocket::bindSocket, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\Network\TCPSocket.cpp
; Line 143
$LN9:
	push	rbx
	sub	rsp, 64					; 00000040H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
; Line 145
	cmp	QWORD PTR [rcx], -1
	mov	rbx, rcx
	je	SHORT $LN5@bindSocket
; Line 153
	mov	eax, 2
; Line 154
	movzx	ecx, dx
	mov	WORD PTR addr4$[rsp], ax
	call	QWORD PTR __imp_htons
; Line 155
	xor	ecx, ecx
	mov	WORD PTR addr4$[rsp+2], ax
	call	QWORD PTR __imp_htonl
; Line 166
	mov	rcx, QWORD PTR [rbx]
	lea	rdx, QWORD PTR addr4$[rsp]
	mov	r8d, 16
	mov	DWORD PTR addr4$[rsp+4], eax
	mov	QWORD PTR addr4$[rsp+8], 0
	call	QWORD PTR __imp_bind
	test	eax, eax
	sete	al
; Line 189
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 64					; 00000040H
	pop	rbx
	ret	0
$LN5@bindSocket:
; Line 169
	xor	al, al
; Line 189
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 64					; 00000040H
	pop	rbx
	ret	0
?bindSocket@TCPSocket@@QEAA_NG@Z ENDP			; TCPSocket::bindSocket
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?listenPort@TCPSocket@@QEAA_NXZ
_TEXT	SEGMENT
this$ = 48
?listenPort@TCPSocket@@QEAA_NXZ PROC			; TCPSocket::listenPort, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\Network\TCPSocket.cpp
; Line 247
$LN8:
	sub	rsp, 40					; 00000028H
; Line 249
	mov	rcx, QWORD PTR [rcx]
	cmp	rcx, -1
	je	SHORT $LN5@listenPort
; Line 256
	mov	edx, 2147483647				; 7fffffffH
	call	QWORD PTR __imp_listen
	test	eax, eax
	sete	al
; Line 264
	add	rsp, 40					; 00000028H
	ret	0
$LN5@listenPort:
; Line 259
	xor	al, al
; Line 264
	add	rsp, 40					; 00000028H
	ret	0
?listenPort@TCPSocket@@QEAA_NXZ ENDP			; TCPSocket::listenPort
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?acceptConnection@TCPSocket@@QEAA_NAEAV1@AEAVIPAddress@@@Z
_TEXT	SEGMENT
addr4$ = 32
addr4Size$ = 48
__$ArrayPad$ = 56
this$ = 96
socket$ = 104
ipaddress$ = 112
?acceptConnection@TCPSocket@@QEAA_NAEAV1@AEAVIPAddress@@@Z PROC ; TCPSocket::acceptConnection, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\Network\TCPSocket.cpp
; Line 270
$LN14:
	push	rbx
	push	rsi
	push	rdi
	sub	rsp, 64					; 00000040H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
; Line 272
	cmp	QWORD PTR [rcx], -1
	mov	rdi, r8
	mov	rbx, rdx
	mov	rsi, rcx
	je	SHORT $LN8@acceptConn
; Line 126
	mov	rcx, QWORD PTR [rdx]
	cmp	rcx, -1
	je	SHORT $LN6@acceptConn
; Line 129
	call	QWORD PTR __imp_closesocket
$LN6@acceptConn:
; Line 283
	xor	eax, eax
; Line 135
	mov	QWORD PTR [rbx], -1
; Line 297
	mov	rcx, QWORD PTR [rsi]
	lea	r8, QWORD PTR addr4Size$[rsp]
	lea	rdx, QWORD PTR addr4$[rsp]
	mov	QWORD PTR addr4$[rsp], rax
	mov	QWORD PTR addr4$[rsp+8], rax
	mov	DWORD PTR addr4Size$[rsp], 16
	call	QWORD PTR __imp_accept
	mov	QWORD PTR [rbx], rax
; Line 298
	cmp	rax, -1
	je	SHORT $LN8@acceptConn
; Line 305
	mov	eax, DWORD PTR addr4$[rsp+4]
	mov	DWORD PTR [rdi], eax
; Line 347
	mov	al, 1
	jmp	SHORT $LN1@acceptConn
$LN8@acceptConn:
; Line 301
	xor	al, al
$LN1@acceptConn:
; Line 348
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 64					; 00000040H
	pop	rdi
	pop	rsi
	pop	rbx
	ret	0
?acceptConnection@TCPSocket@@QEAA_NAEAV1@AEAVIPAddress@@@Z ENDP ; TCPSocket::acceptConnection
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?connectSocket@TCPSocket@@QEAA_NAEAVIPAddress@@G@Z
_TEXT	SEGMENT
addr4$ = 32
__$ArrayPad$ = 48
this$ = 80
ipaddress$ = 88
port$ = 96
?connectSocket@TCPSocket@@QEAA_NAEAVIPAddress@@G@Z PROC	; TCPSocket::connectSocket, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\Network\TCPSocket.cpp
; Line 355
$LN11:
	mov	QWORD PTR [rsp+32], rbx
	push	rdi
	sub	rsp, 64					; 00000040H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
; Line 357
	cmp	QWORD PTR [rcx], -1
	mov	rdi, rdx
	mov	rbx, rcx
	je	SHORT $LN7@connectSoc
; Line 365
	mov	eax, 2
; Line 366
	movzx	ecx, r8w
	mov	WORD PTR addr4$[rsp], ax
	call	QWORD PTR __imp_htons
; Line 378
	mov	rcx, QWORD PTR [rbx]
	lea	rdx, QWORD PTR addr4$[rsp]
	mov	WORD PTR addr4$[rsp+2], ax
	mov	r8d, 16
	mov	eax, DWORD PTR [rdi]
	mov	DWORD PTR addr4$[rsp+4], eax
	mov	QWORD PTR addr4$[rsp+8], 0
	call	QWORD PTR __imp_connect
	test	eax, eax
	sete	al
	jmp	SHORT $LN1@connectSoc
$LN7@connectSoc:
; Line 380
	xor	al, al
$LN1@connectSoc:
; Line 399
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	mov	rbx, QWORD PTR [rsp+104]
	add	rsp, 64					; 00000040H
	pop	rdi
	ret	0
?connectSocket@TCPSocket@@QEAA_NAEAVIPAddress@@G@Z ENDP	; TCPSocket::connectSocket
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?sendData@TCPSocket@@QEAA_NPEBD_K@Z
_TEXT	SEGMENT
this$ = 48
data$ = 56
size$ = 64
?sendData@TCPSocket@@QEAA_NPEBD_K@Z PROC		; TCPSocket::sendData, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\Network\TCPSocket.cpp
; Line 440
$LN22:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rsi
	mov	QWORD PTR [rsp+24], rdi
	push	r14
	sub	rsp, 32					; 00000020H
; Line 442
	cmp	QWORD PTR [rcx], -1
	mov	rdi, r8
	mov	rsi, rdx
	mov	r14, rcx
	je	SHORT $LN7@sendData
; Line 449
	test	rdx, rdx
	je	SHORT $LN7@sendData
	test	r8, r8
	je	SHORT $LN7@sendData
; Line 456
	xor	ebx, ebx
$LL4@sendData:
; Line 461
	mov	rcx, QWORD PTR [r14]
	lea	rdx, QWORD PTR [rbx+rsi]
	mov	r8d, edi
	xor	r9d, r9d
	sub	r8d, ebx
	call	QWORD PTR __imp_send
; Line 466
	test	eax, eax
	js	SHORT $LN7@sendData
; Line 471
	cdqe
	add	rbx, rax
; Line 472
	cmp	rbx, rdi
	jb	SHORT $LL4@sendData
; Line 475
	mov	al, 1
	jmp	SHORT $LN1@sendData
$LN7@sendData:
; Line 452
	xor	al, al
$LN1@sendData:
; Line 476
	mov	rbx, QWORD PTR [rsp+48]
	mov	rsi, QWORD PTR [rsp+56]
	mov	rdi, QWORD PTR [rsp+64]
	add	rsp, 32					; 00000020H
	pop	r14
	ret	0
?sendData@TCPSocket@@QEAA_NPEBD_K@Z ENDP		; TCPSocket::sendData
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?receiveData@TCPSocket@@QEAA_NPEAD_K@Z
_TEXT	SEGMENT
this$ = 48
data$ = 56
size$ = 64
?receiveData@TCPSocket@@QEAA_NPEAD_K@Z PROC		; TCPSocket::receiveData, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\Network\TCPSocket.cpp
; Line 516
$LN22:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rsi
	mov	QWORD PTR [rsp+24], rdi
	push	r14
	sub	rsp, 32					; 00000020H
; Line 518
	cmp	QWORD PTR [rcx], -1
	mov	rdi, r8
	mov	rsi, rdx
	mov	r14, rcx
	je	SHORT $LN7@receiveDat
; Line 525
	test	rdx, rdx
	je	SHORT $LN7@receiveDat
	test	r8, r8
	je	SHORT $LN7@receiveDat
; Line 532
	xor	ebx, ebx
$LL4@receiveDat:
; Line 537
	mov	rcx, QWORD PTR [r14]
	lea	rdx, QWORD PTR [rbx+rsi]
	mov	r8d, edi
	xor	r9d, r9d
	sub	r8d, ebx
	call	QWORD PTR __imp_recv
; Line 542
	test	eax, eax
	js	SHORT $LN7@receiveDat
; Line 547
	cdqe
	add	rbx, rax
; Line 548
	cmp	rbx, rdi
	jb	SHORT $LL4@receiveDat
; Line 551
	mov	al, 1
	jmp	SHORT $LN1@receiveDat
$LN7@receiveDat:
; Line 528
	xor	al, al
$LN1@receiveDat:
; Line 552
	mov	rbx, QWORD PTR [rsp+48]
	mov	rsi, QWORD PTR [rsp+56]
	mov	rdi, QWORD PTR [rsp+64]
	add	rsp, 32					; 00000020H
	pop	r14
	ret	0
?receiveData@TCPSocket@@QEAA_NPEAD_K@Z ENDP		; TCPSocket::receiveData
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?setAddress@IPAddress@@QEAAXUin_addr@@@Z
_TEXT	SEGMENT
this$ = 8
ipaddress$ = 16
?setAddress@IPAddress@@QEAAXUin_addr@@@Z PROC		; IPAddress::setAddress, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\Network\IPAddress.h
; Line 79
	mov	DWORD PTR [rcx], edx
; Line 80
	ret	0
?setAddress@IPAddress@@QEAAXUin_addr@@@Z ENDP		; IPAddress::setAddress
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?getAddress@IPAddress@@QEBA?AUin_addr@@XZ
_TEXT	SEGMENT
this$ = 8
__$ReturnUdt$ = 16
?getAddress@IPAddress@@QEBA?AUin_addr@@XZ PROC		; IPAddress::getAddress, COMDAT
; File D:\Dev\GitHub\vtools\netcpy\Network\IPAddress.h
; Line 110
	mov	eax, DWORD PTR [rcx]
	mov	DWORD PTR [rdx], eax
	mov	rax, rdx
; Line 111
	ret	0
?getAddress@IPAddress@@QEBA?AUin_addr@@XZ ENDP		; IPAddress::getAddress
_TEXT	ENDS
END
