; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32537.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	main
EXTRN	_read:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN4
	DD	imagerel $LN4+34
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Ogtpy
;	COMDAT main
_TEXT	SEGMENT
ch$ = 48
main	PROC						; COMDAT
; File D:\Dev\eal\asmwindows\main.cpp
; Line 15
$LN4:
	sub	rsp, 40					; 00000028H
; Line 20
	mov	r8d, 1
	mov	BYTE PTR ch$[rsp], 0
	lea	rdx, QWORD PTR ch$[rsp]
	xor	ecx, ecx
	call	_read
; Line 21
	xor	eax, eax
; Line 22
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
END
