; CPP :
; #include <fcntl.h>
; #include <io.h>
; #include <cstdint>
; #include <cstddef>

; #define CONSOLE_INPUT_FILEDESC 0
; #define CONSOLE_OUTPUT_FILEDESC 1
; #define CONSOLE_ERROR_FILEDESC 2

; #define CONSOLE_WRITE _write
; #define CONSOLE_READ _read
; #define CONSOLE_FLUSH _commit

; int main()
; {
;     char ch = 't';
;     CONSOLE_WRITE(CONSOLE_OUTPUT_FILEDESC, &ch, 1);
;     return 0;
; }







; Basic compile


; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32537.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	main
EXTRN	_write:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN4
	DD	imagerel $LN4+35
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Ogtpy
;	COMDAT main
_TEXT	SEGMENT
ch$ = 48
main	PROC						; COMDAT
; File D:\Dev\eal\asmwindows\main.cpp
; Line 15
$LN4:
	sub	rsp, 40					; 00000028H
; Line 17
	mov	r8d, 1
	mov	BYTE PTR ch$[rsp], 116			; 00000074H
	mov	ecx, r8d
	lea	rdx, QWORD PTR ch$[rsp]
	call	_write
; Line 18
	xor	eax, eax
; Line 19
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
END




; Good settings compile


; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32537.0 

include listing.inc

INCLUDELIB OLDNAMES

EXTRN	_write:PROC
EXTRN	__security_check_cookie:PROC
PUBLIC	main
EXTRN	__GSHandlerCheck:PROC
EXTRN	__security_cookie:QWORD
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN4
	DD	imagerel $LN4+63
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	011319H
	DD	06204H
	DD	imagerel __GSHandlerCheck
	DD	028H
xdata	ENDS
; Function compile flags: /Ogtpy
;	COMDAT main
_TEXT	SEGMENT
ch$ = 32
__$ArrayPad$ = 40
main	PROC						; COMDAT
; File D:\Dev\lowout\main.cpp
; Line 61
$LN4:
	sub	rsp, 56					; 00000038H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
; Line 64
	mov	r8d, 1
	mov	BYTE PTR ch$[rsp], 116			; 00000074H
	mov	ecx, r8d
	lea	rdx, QWORD PTR ch$[rsp]
	call	_write
; Line 65
	xor	eax, eax
; Line 66
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 56					; 00000038H
	ret	0
main	ENDP
_TEXT	ENDS
END
