; CPP :
; #include <fcntl.h>
; #include <io.h>
; #include <cstdint>
; #include <cstddef>

; #define CONSOLE_INPUT_FILEDESC 0
; #define CONSOLE_OUTPUT_FILEDESC 1
; #define CONSOLE_ERROR_FILEDESC 2

; #define CONSOLE_WRITE _write
; #define CONSOLE_READ _read
; #define CONSOLE_FLUSH _commit


; inline int32_t StringLength(const char* array)
; {
;     int i = -1;
;     while (array[++i]);
;     return i;
; }

; int main()
; {
;     char ch[] = "Test\n";
;     CONSOLE_WRITE(CONSOLE_OUTPUT_FILEDESC,
;         ch, static_cast<unsigned int>(StringLength(ch))
;     );
;     return 0;
; }


; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32537.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?StringLength@@YAHPEBD@Z			; StringLength
PUBLIC	main
PUBLIC	??_C@_05FIGNMLPE@Test?6@			; `string'
EXTRN	_write:PROC
EXTRN	__GSHandlerCheck:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__security_cookie:QWORD
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN11
	DD	imagerel $LN11+111
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT ??_C@_05FIGNMLPE@Test?6@
CONST	SEGMENT
??_C@_05FIGNMLPE@Test?6@ DB 'Test', 0aH, 00H		; `string'
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	011319H
	DD	06204H
	DD	imagerel __GSHandlerCheck
	DD	028H
xdata	ENDS
; Function compile flags: /Ogtpy
;	COMDAT main
_TEXT	SEGMENT
ch$ = 32
__$ArrayPad$ = 40
main	PROC						; COMDAT
; File D:\Dev\eal\asmwindows\main.cpp
; Line 23
$LN11:
	sub	rsp, 56					; 00000038H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
; Line 24
	mov	eax, DWORD PTR ??_C@_05FIGNMLPE@Test?6@
; Line 17
	mov	r8d, -1
; Line 24
	mov	DWORD PTR ch$[rsp], eax
	movzx	eax, WORD PTR ??_C@_05FIGNMLPE@Test?6@+4
	mov	WORD PTR ch$[rsp+4], ax
; Line 17
	lea	rax, QWORD PTR ch$[rsp]
	dec	rax
	npad	9
$LL4@main:
; Line 18
	inc	r8d
	lea	rax, QWORD PTR [rax+1]
	cmp	BYTE PTR [rax], 0
	jne	SHORT $LL4@main
; Line 25
	lea	rdx, QWORD PTR ch$[rsp]
	mov	ecx, 1
	call	_write
; Line 28
	xor	eax, eax
; Line 29
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 56					; 00000038H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?StringLength@@YAHPEBD@Z
_TEXT	SEGMENT
array$ = 8
?StringLength@@YAHPEBD@Z PROC				; StringLength, COMDAT
; File D:\Dev\eal\asmwindows\main.cpp
; Line 17
	mov	eax, -1
	dec	rcx
	npad	8
$LL2@StringLeng:
; Line 18
	inc	eax
	lea	rcx, QWORD PTR [rcx+1]
	cmp	BYTE PTR [rcx], 0
	jne	SHORT $LL2@StringLeng
; Line 20
	ret	0
?StringLength@@YAHPEBD@Z ENDP				; StringLength
_TEXT	ENDS
END
