; CPP :
; int main()
; {
;     return 0;
; }


; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32537.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	main
; Function compile flags: /Odtp
_TEXT	SEGMENT
main	PROC
; File D:\Dev\eal\asmwindows\main.cpp
; Line 26
	xor	eax, eax
; Line 27
	ret	0
main	ENDP
_TEXT	ENDS
END
